INSERT INTO framework_versions (framework_short, framework_name, jurisdiction, version, status, last_reviewed_at, reviewed_by, sector_news) VALUES
('DIFC_DPL','DIFC Data Protection Law No. 5 of 2020','AE','2026.1','active','2026-06-01','Aman Pareek, International Business Lawyer','The DIFC Commissioner of Data Protection can fine up to USD 100,000 for data-subject-rights breaches and USD 50,000 for unlawful processing or unlawful transfer; registration with the Commissioner is mandatory.'),
('ADGM_DPR','ADGM Data Protection Regulations 2021','AE','2026.1','active','2026-06-01','Aman Pareek, International Business Lawyer','ADGM operates a GDPR-aligned regime with mandatory registration and a Commissioner empowered to impose administrative fines; it applies to any controller established in ADGM.'),
('SAUDI_PDPL','Saudi Personal Data Protection Law (SDAIA)','SA','2026.1','active','2026-06-01','Aman Pareek, International Business Lawyer','SDAIA enforcement committees issued 48 PDPL violation decisions in 2025-26, including for marketing without consent and processing without a legal basis; fines reach SAR 5,000,000, doubled for repeat offences.'),
('QATAR_PDPPL','Qatar Personal Data Privacy Protection Law (Law 13 of 2016)','QA','2026.1','active','2026-06-01','Aman Pareek, International Business Lawyer','Qatar NDPO can fine QAR 1,000,000 to QAR 5,000,000 per violation; breaches must be notified within 72 hours.'),
('UAE_DHA','UAE Health Advertising (MOHAP / DHA / DOH)','AE','2026.1','active','2026-06-01','Aman Pareek, International Business Lawyer','The DHA and MOHAP require permits for medical advertising and ban unsubstantiated health claims; the DHA actively actions clinics over social-media medical ads and misuse of the DHA logo.'),
('UAE_CONSUMER','UAE Consumer Protection Law (Federal Law 15 of 2020)','AE','2026.1','active','2026-06-01','Aman Pareek, International Business Lawyer','The UAE Ministry of Economy enforces clear pricing and honest commercial practices; misleading prices and terms draw penalties and product/marketing suspension.'),
('UAE_ECOMMERCE','UAE E-Commerce & Electronic Transactions (Federal Decree-Law 46 of 2021)','AE','2026.1','active','2026-06-01','Aman Pareek, International Business Lawyer','UAE e-commerce rules require trader identification and clear terms on online stores serving UAE consumers.')
ON CONFLICT (framework_short) DO UPDATE SET jurisdiction=EXCLUDED.jurisdiction, status='active', sector_news=EXCLUDED.sector_news;
