-- B: online-advertising / Google laws (jurisdiction-gated). CAN-SPAM (US) + Google E-E-A-T author signal (global). Idempotent.
INSERT INTO framework_versions (framework_name, framework_short, jurisdiction, version, rules_count, last_reviewed_at, reviewed_by, status, notes)
VALUES ('CAN-SPAM Act','US_CAN_SPAM','US','2025.1',2,'2026-06-03','Tamazia Engine','active','US commercial email marketing law (FTC); USD 53,088 per email')
ON CONFLICT (framework_short) DO NOTHING;

INSERT INTO compliance_rules (framework_short,rule_id,description,regex_pattern,url_check,severity,citation_url,enforcement_example,exceptions,active,rule_type,trigger_pattern,layman_explanation,tamazia_fix_short,service_page_path,pricing_tier)
VALUES
('US_CAN_SPAM','CANSPAM_ADDR','Commercial email must include a valid physical postal address','(\d+\s+[A-Z][a-zA-Z]+\s+(Street|St|Avenue|Ave|Road|Rd|Boulevard|Blvd|Suite|Ste|Floor|Drive|Dr|Lane|Way)|P\.?O\.?\s?Box\s?\d|\b[A-Z]{2}\s\d{5}(-\d{4})?\b)','homepage','P2','https://www.ftc.gov/business-guidance/resources/can-spam-act-compliance-guide-business','FTC under CAN-SPAM: up to USD 53,088 per email; FTC v Verkada USD 2.95M (2024).','None',TRUE,'trigger_then_check','(subscribe|newsletter|sign[- ]?up for (our )?(email|updates|newsletter|mailing)|mailing list|email updates|join (our )?(list|mailing)|get the latest|email me)','You market by email but we could not find a valid physical postal address. CAN-SPAM requires it on every commercial email, fined per email up to USD 53,088.','Tamazia adds a CAN-SPAM-compliant postal address and footer to your email programme.','/services/regulatory-compliance/','Authority'),
('US_CAN_SPAM','CANSPAM_OPTOUT','Commercial email must offer a clear, working opt-out','(unsubscribe|opt[- ]?out|email preferences|manage (your )?(subscription|preferences|email)|update your preferences|stop receiving)','homepage','P2','https://www.ftc.gov/business-guidance/resources/can-spam-act-compliance-guide-business','FTC under CAN-SPAM: up to USD 53,088 per email; FTC v Verkada USD 2.95M (2024).','None',TRUE,'trigger_then_check','(subscribe|newsletter|sign[- ]?up for (our )?(email|updates|newsletter|mailing)|mailing list|email updates|join (our )?(list|mailing)|get the latest|email me)','Your site invites email sign-ups but shows no clear unsubscribe route. CAN-SPAM requires a conspicuous opt-out honoured within 10 business days.','Tamazia wires a compliant, honoured unsubscribe into your email capture.','/services/regulatory-compliance/','Authority'),
('GOOGLE_EEAT','EEAT_AUTHOR','Published content shows author / expertise signals (E-E-A-T)','(written by|author|by [A-Z][a-z]+ [A-Z][a-z]+|our (experts?|team|specialists?|solicitors?|consultants?)|reviewed by|qualifications|years of experience|admitted in)','homepage','P2','https://developers.google.com/search/docs/fundamentals/creating-helpful-content','Google ranking systems + manual actions: content without authorship/expertise is demoted under helpful-content/E-E-A-T, costing visibility and AI citations.','None',TRUE,'trigger_then_check','(/blog|/insights?|/articles?|/news|/resources|/guides?|latest (news|articles|insights)|read more)','You publish content but it carries no clear author or expertise signals. Google E-E-A-T rewards named, qualified authors, and AI engines cite the same authoritative pages.','Tamazia adds author bios, credentials and review signals to your content.','/services/regulatory-compliance/','Authority')
ON CONFLICT DO NOTHING;
