-- Middle East data-protection map completion (2026-06-30). Multi-source-verified (Research Report 2 + DLA Piper,
-- Akin Gump, Clyde & Co, Chambers, ICLG, IAPP, Library of Congress). My jurisdiction registry already routes
-- BH/OM/EG/JO/IL; these were the only gulf states with NO framework in the catalogue. Each gets a framework_versions
-- row + a baseline privacy-notice rule (modelled on SAUDI_PDPL). Kuwait intentionally omitted (CITRA sectoral only,
-- no omnibus data-protection law). Reversible: DELETE the 5 framework_short + their rules.
INSERT INTO framework_versions (framework_name, framework_short, jurisdiction, version, status, notes) VALUES
 ('Bahrain Personal Data Protection Law (Law No. 30 of 2018)','BAHRAIN_PDPL','BH','2026.1','active','Regulator: Personal Data Protection Authority (PDPA, MoJ). In force 2019-08-01. Source: Law 30/2018; DLA Piper; Akin Gump.'),
 ('Oman Personal Data Protection Law (Royal Decree 6/2022)','OMAN_PDPL','OM','2026.1','active','Regulator: MTCIT. Fully enforceable 2026-02-05 (Exec Regs Ministerial Decision 34/2024). Source: RD 6/2022; Clyde & Co.'),
 ('Egypt Personal Data Protection Law (Law No. 151 of 2020)','EGYPT_PDPL','EG','2026.1','active','Regulator: PDPC. Exec Regs Decree 816/2025; full enforcement ~2026-11. Source: Law 151/2020; Chambers; ICLG.'),
 ('Jordan Personal Data Protection Law (Law No. 24 of 2023)','JORDAN_PDPL','JO','2026.1','active','Regulator: Data Protection Council (MoDEE). In force 2024-03-17. Source: Law 24/2023; Clyde & Co; DLA Piper.'),
 ('Israel Protection of Privacy Law 5741-1981 (Amendment 13)','ISRAEL_PPL','IL','2026.1','active','Regulator: Privacy Protection Authority (PPA). Amendment 13 effective 2025-08-14. Source: PPL 5741-1981; IAPP; Library of Congress.')
ON CONFLICT (framework_short) DO NOTHING;
INSERT INTO compliance_rules (framework_short, rule_id, description, rule_type, regex_pattern, url_check, severity, sector_relevance, active, statutory_citation, layman_explanation, tamazia_fix_short) VALUES
 ('BAHRAIN_PDPL','BAHRAIN_NOTICE','Public-facing privacy notice required for sites processing personal data of Bahrain residents (transparency, lawful basis, data-subject rights).','must_appear','(privacy (policy|notice)|data protection|personal data)','/privacy','P1','{}',TRUE,'Bahrain PDPL, Law No. 30 of 2018 (PDPA).','A site collecting Bahrain residents'' personal data must publish a clear privacy notice.','Publish a Bahrain-PDPL-compliant privacy policy covering purposes, lawful basis and data-subject rights.'),
 ('OMAN_PDPL','OMAN_NOTICE','Public-facing privacy notice required for sites processing personal data of Oman residents.','must_appear','(privacy (policy|notice)|data protection|personal data)','/privacy','P1','{}',TRUE,'Oman PDPL, Royal Decree 6/2022 (MTCIT); fully enforceable 2026-02-05.','A site collecting Oman residents'' personal data must publish a clear privacy notice.','Publish an Oman-PDPL-compliant privacy policy.'),
 ('EGYPT_PDPL','EGYPT_NOTICE','Public-facing privacy notice required for sites processing personal data of Egypt residents.','must_appear','(privacy (policy|notice)|data protection|personal data)','/privacy','P1','{}',TRUE,'Egypt PDPL, Law No. 151 of 2020 (PDPC); Exec Regs Decree 816/2025.','A site collecting Egypt residents'' personal data must publish a clear privacy notice.','Publish an Egypt-PDPL-compliant privacy policy.'),
 ('JORDAN_PDPL','JORDAN_NOTICE','Public-facing privacy notice required for sites processing personal data of Jordan residents.','must_appear','(privacy (policy|notice)|data protection|personal data)','/privacy','P1','{}',TRUE,'Jordan PDPL, Law No. 24 of 2023 (Data Protection Council/MoDEE); in force 2024-03-17.','A site collecting Jordan residents'' personal data must publish a clear privacy notice.','Publish a Jordan-PDPL-compliant privacy policy.'),
 ('ISRAEL_PPL','ISRAEL_NOTICE','Public-facing privacy notice required for sites processing personal data of Israeli residents.','must_appear','(privacy (policy|notice)|data protection|personal data)','/privacy','P1','{}',TRUE,'Israel Protection of Privacy Law 5741-1981, Amendment 13 (PPA); effective 2025-08-14.','A site collecting Israeli residents'' personal data must publish a clear privacy notice.','Publish an Israel-PPL-compliant privacy policy.');
