'use strict';
// WS3 · gap-ledger — the write side of the gap → root-cause → PR → re-mint loop.
//
// When the Layer-3 Claude safeguard finds a minted audit MISSING a law that should apply (or carrying a wrong
// one / a missed live error / weak copy), it calls recordGap() here. That does TWO things:
//   1. UPSERTs a row into the Neon `engine_gap_fixes` table (the machine ledger; columns: lead_ref, audit_hash,
//      domain, sector, gap_type, gap_detail jsonb, root_cause, fix_pr_url, fixture_path, status, detected_at,
//      resolved_at, detected_batch). De-dupes on (audit_hash, gap_type, signature) so the same gap on a re-scan
//      updates the open row instead of piling up duplicates.
//   2. Appends a human-readable bullet to the ops/CLAUDE-GAP-LEDGER.md ledger (create-if-missing, DEFENSIVELY —
//      WS4 owns committing that markdown file; this helper only WRITES to it at runtime and never stages it).
//
// updateGap() flips status as the loop advances (open → pr_open → merged → reminted → verified) and stamps
// fix_pr_url / fixture_path / resolved_at.
//
// Neon writes go via the HTTP /sql endpoint (same transport as src/lib/cost-ledger.js) so there is no psql
// dependency and no per-call process spawn. NEVER THROWS — a ledger outage must never break the mint/safeguard
// path; every function returns a small status object. Self-provisions the table (CREATE TABLE IF NOT EXISTS)
// so it works even before the migration is applied.
//
// DRY MODE: pass { dry: true } (or set GAP_LEDGER_DRY=1) to PRINT the SQL it WOULD run and skip the Neon write
// entirely — used for offline self-testing so no test rows ever land in live Neon. The markdown append is also
// skipped in dry mode (it only logs what it would append).

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const NEON = () => process.env.NEON_URL || process.env.NEON_CONNECTION_STRING || process.env.NEON_DATABASE_URL;
const ROOT = path.resolve(__dirname, '..', '..');
const LEDGER_MD = path.join(ROOT, 'ops', 'CLAUDE-GAP-LEDGER.md');
const VALID_GAP_TYPES = new Set(['law', 'live_error', 'competitor', 'copy']);
const VALID_STATUS = new Set(['open', 'pr_open', 'merged', 'reminted', 'verified']);

const esc = v => String(v == null ? '' : v).replace(/'/g, "''");
const isDry = (opts) => !!(opts && opts.dry) || process.env.GAP_LEDGER_DRY === '1';

// One Neon HTTP /sql round-trip. Returns { ok, rows } or { ok:false }. Never throws.
async function sql(query, opts) {
  const url = NEON();
  if (isDry(opts)) { console.log('[gap-ledger][dry] SQL:\n' + query); return { ok: true, dry: true, rows: [] }; }
  if (!url) return { ok: false, reason: 'no_neon_url' };
  try {
    const host = url.replace(/.*@([^/]+)\/.*/, '$1');
    const r = await fetch('https://' + host + '/sql', {
      method: 'POST',
      headers: { 'Neon-Connection-String': url, 'Content-Type': 'application/json' },
      body: JSON.stringify({ query, params: [] }),
      signal: AbortSignal.timeout(10000),
    });
    if (!r.ok) return { ok: false, reason: 'http_' + r.status };
    const d = await r.json();
    return { ok: true, rows: d.rows || d.results || [] };
  } catch (e) { return { ok: false, reason: e.message }; }
}

let _ensured = false;
async function ensure(opts) {
  if (_ensured && !isDry(opts)) return { ok: true };
  // Mirror migrations/2026-06-15-claude-layer.sql exactly so a runtime-provisioned table matches the migration.
  const ddl = `CREATE TABLE IF NOT EXISTS engine_gap_fixes (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_ref       text,
  audit_hash     text,
  domain         text,
  sector         text,
  gap_type       text,
  gap_detail     jsonb,
  root_cause     text,
  fix_pr_url     text,
  fixture_path   text,
  status         text DEFAULT 'open',
  detected_at    timestamptz DEFAULT now(),
  resolved_at    timestamptz,
  detected_batch text
)`;
  const r = await sql(ddl, opts);
  if (r.ok && !r.dry) _ensured = true;
  return r;
}

// Stable signature for de-dupe: the gap is "the same gap" if it is the same (audit_hash, gap_type, key fact).
// Key fact = the law/error code at the centre of the gap (gap_detail.framework_short || .law || .rule_id ||
// .code), falling back to a hash of the whole detail blob. Stored inside gap_detail._sig so a re-scan UPSERTs.
function gapSignature(gap) {
  const d = gap.gap_detail || {};
  const key = d.framework_short || d.law || d.rule_id || d.code || d.competitor || '';
  if (key) return String(key);
  try { return crypto.createHash('sha1').update(JSON.stringify(d)).digest('hex').slice(0, 16); }
  catch (_e) { return 'na'; }
}

// Append a human-readable line to ops/CLAUDE-GAP-LEDGER.md. Create-if-missing DEFENSIVELY (WS4 commits the file;
// we only ever append at runtime and never `git add` it). Never throws.
function appendLedgerMd(gap, sig, opts) {
  const ts = new Date().toISOString();
  const detail = gap.gap_detail ? (() => { try { return JSON.stringify(gap.gap_detail); } catch (_e) { return '{}'; } })() : '{}';
  const line = `- ${ts} · **${gap.gap_type || 'gap'}** · \`${gap.domain || '?'}\` (${gap.sector || '?'}) · sig=\`${sig}\` · audit=\`${gap.audit_hash || '?'}\` · root_cause: ${gap.root_cause || '(pending)'} · detail: \`${detail}\`\n`;
  if (isDry(opts)) { console.log('[gap-ledger][dry] would append to ' + LEDGER_MD + ':\n' + line.trimEnd()); return { ok: true, dry: true }; }
  try {
    if (!fs.existsSync(LEDGER_MD)) {
      // create-if-missing header so the file is valid even before WS4 commits its canonical version.
      const header = '# CLAUDE-GAP-LEDGER\n\nHuman-readable log of audit gaps caught by the Layer-3 safeguard and the fix that closed each one. One bullet per gap; the machine record lives in the `engine_gap_fixes` Neon table. (Appended at runtime by `src/lib/gap-ledger.js`.)\n\n';
      fs.mkdirSync(path.dirname(LEDGER_MD), { recursive: true });
      fs.writeFileSync(LEDGER_MD, header, 'utf8');
    }
    fs.appendFileSync(LEDGER_MD, line, 'utf8');
    return { ok: true, path: LEDGER_MD };
  } catch (e) { return { ok: false, reason: e.message }; }
}

/**
 * recordGap(gap, opts) — UPSERT an engine_gap_fixes row + append a ledger bullet.
 *   gap = { lead_ref?, audit_hash, domain, sector, gap_type, gap_detail (object), root_cause?, detected_batch? }
 *   opts = { dry? }   (dry → print SQL + the ledger line, write nothing)
 * Returns { ok, gapSig, db:{...}, md:{...} }. Never throws.
 */
async function recordGap(gap = {}, opts = {}) {
  const out = { ok: false, gapSig: null, db: null, md: null };
  try {
    const gt = String(gap.gap_type || '').trim();
    if (!VALID_GAP_TYPES.has(gt)) return { ...out, reason: 'bad_gap_type:' + gt };
    const sig = gapSignature(gap);
    out.gapSig = sig;

    // stamp the signature inside gap_detail so the row is self-describing + the UPSERT can find its match.
    const detail = Object.assign({}, gap.gap_detail || {}, { _sig: sig });
    const detailJson = (() => { try { return JSON.stringify(detail); } catch (_e) { return '{}'; } })();

    await ensure(opts);

    // De-dupe on (audit_hash, gap_type, _sig) while the row is still open/in-flight: re-scans refresh detail +
    // detected_at instead of inserting a duplicate. A row already resolved (merged/reminted/verified) is left
    // alone and a NEW open row is created (the gap recurred after being closed — worth its own record).
    const where = `audit_hash = '${esc(gap.audit_hash)}' AND gap_type = '${esc(gt)}' AND gap_detail->>'_sig' = '${esc(sig)}' AND status IN ('open','pr_open')`;
    const upd = `UPDATE engine_gap_fixes SET gap_detail = '${esc(detailJson)}'::jsonb, root_cause = COALESCE(NULLIF('${esc(gap.root_cause)}',''), root_cause), domain = '${esc(gap.domain)}', sector = '${esc(gap.sector)}', lead_ref = COALESCE(NULLIF('${esc(gap.lead_ref)}',''), lead_ref), detected_batch = COALESCE(NULLIF('${esc(gap.detected_batch)}',''), detected_batch), detected_at = now() WHERE ${where} RETURNING id`;

    let dbRes = await sql(upd, opts);
    let inserted = false;
    if (dbRes.dry) {
      // in dry mode also print the INSERT branch so the operator sees both possible writes.
    } else if (dbRes.ok && Array.isArray(dbRes.rows) && dbRes.rows.length) {
      // updated an in-flight open row.
    } else {
      inserted = true;
    }

    if (inserted || isDry(opts)) {
      const ins = `INSERT INTO engine_gap_fixes (lead_ref, audit_hash, domain, sector, gap_type, gap_detail, root_cause, status, detected_batch) VALUES ('${esc(gap.lead_ref)}', '${esc(gap.audit_hash)}', '${esc(gap.domain)}', '${esc(gap.sector)}', '${esc(gt)}', '${esc(detailJson)}'::jsonb, NULLIF('${esc(gap.root_cause)}',''), 'open', NULLIF('${esc(gap.detected_batch)}','')) RETURNING id`;
      const insRes = await sql(ins, opts);
      out.db = { ok: insRes.ok, action: 'insert', reason: insRes.reason, dry: !!insRes.dry };
    } else {
      out.db = { ok: dbRes.ok, action: 'update', reason: dbRes.reason };
    }

    out.md = appendLedgerMd(gap, sig, opts);
    out.ok = !!(out.db && out.db.ok);
    return out;
  } catch (e) { return { ...out, reason: e.message }; }
}

/**
 * updateGap(match, fields, opts) — advance a gap row as the loop progresses.
 *   match  = { audit_hash, gap_type?, gap_sig? }  (identifies the row; gap_sig matches gap_detail->>'_sig')
 *   fields = { status?, fix_pr_url?, fixture_path?, root_cause? }   (only provided fields are written)
 *   On status 'merged'|'reminted'|'verified', resolved_at is stamped automatically.
 * Returns { ok, updated, reason? }. Never throws.
 */
async function updateGap(match = {}, fields = {}, opts = {}) {
  try {
    if (!match.audit_hash) return { ok: false, reason: 'no_audit_hash' };
    if (fields.status && !VALID_STATUS.has(fields.status)) return { ok: false, reason: 'bad_status:' + fields.status };
    const sets = [];
    if (fields.status) sets.push(`status = '${esc(fields.status)}'`);
    if (fields.fix_pr_url != null) sets.push(`fix_pr_url = '${esc(fields.fix_pr_url)}'`);
    if (fields.fixture_path != null) sets.push(`fixture_path = '${esc(fields.fixture_path)}'`);
    if (fields.root_cause != null) sets.push(`root_cause = '${esc(fields.root_cause)}'`);
    if (['merged', 'reminted', 'verified'].includes(fields.status)) sets.push('resolved_at = now()');
    if (!sets.length) return { ok: false, reason: 'no_fields' };

    const conds = [`audit_hash = '${esc(match.audit_hash)}'`];
    if (match.gap_type) conds.push(`gap_type = '${esc(match.gap_type)}'`);
    if (match.gap_sig) conds.push(`gap_detail->>'_sig' = '${esc(match.gap_sig)}'`);
    const q = `UPDATE engine_gap_fixes SET ${sets.join(', ')} WHERE ${conds.join(' AND ')} RETURNING id`;

    const r = await sql(q, opts);
    return { ok: !!r.ok, updated: r.dry ? '(dry)' : (Array.isArray(r.rows) ? r.rows.length : 0), reason: r.reason };
  } catch (e) { return { ok: false, reason: e.message }; }
}

module.exports = { recordGap, updateGap, gapSignature, LEDGER_MD, VALID_GAP_TYPES, VALID_STATUS };

// CLI self-test (dry-only by design — NEVER writes to live Neon):
//   node src/lib/gap-ledger.js            → prints the UPSERT + INSERT SQL + the ledger line for a sample gap
if (require.main === module) {
  process.env.GAP_LEDGER_DRY = '1';
  (async () => {
    const r = await recordGap({
      audit_hash: 'SELFTEST_HASH', domain: 'example.co.uk', sector: 'law-firms', gap_type: 'law',
      gap_detail: { framework_short: 'UK_SRA_COC', expected: true, found: false, why: 'sector core missing from mint' },
      root_cause: 'jurisdiction-router SECTOR_MAP[law-firms] (self-test, no real fix)', detected_batch: 'selftest',
    }, { dry: true });
    console.log('\n[gap-ledger] recordGap(dry) →', JSON.stringify({ ok: r.ok, gapSig: r.gapSig, db: r.db, md: { ok: r.md && r.md.ok, dry: r.md && r.md.dry } }));
    const u = await updateGap({ audit_hash: 'SELFTEST_HASH', gap_type: 'law', gap_sig: r.gapSig }, { status: 'pr_open', fix_pr_url: 'https://github.com/Tamaziaa/tamazia-cowork-os/pull/0', fixture_path: 'eval/audit-gaps.json' }, { dry: true });
    console.log('[gap-ledger] updateGap(dry) →', JSON.stringify(u));
  })();
}
