-- Phase V5 · Layer-3 Claude Safeguard — schema (ADDITIVE ONLY)
-- Companion to schema/canonical-schema.json (ensure-schema.js provisions columns + tables automatically;
-- this file is the human-runnable record + the VIEW and GRANTs that ensure-schema does not handle).
-- Touches NONE of the off-limits families (audit_*/compliance_*/framework_*/classifier_*/pointer_*/scanner_cache).
-- Apply:  node scripts/ensure-schema.js   (preferred, idempotent)   OR   psql "$NEON_URL" -f migrations/2026-06-15-claude-layer.sql

-- ── Layer-3 clearance flags on leads (plain booleans, set by the safeguard runner; mirror audit_verified) ──
ALTER TABLE leads ADD COLUMN IF NOT EXISTS claude_lead_cleared  boolean      DEFAULT false;   -- info verified + Tier-1 attempted
ALTER TABLE leads ADD COLUMN IF NOT EXISTS claude_audit_cleared boolean      DEFAULT false;   -- audit checked vs real laws/site/competitors
ALTER TABLE leads ADD COLUMN IF NOT EXISTS claude_touch_cleared boolean      DEFAULT false;   -- every touch verified before send
ALTER TABLE leads ADD COLUMN IF NOT EXISTS claude_cleared       boolean      DEFAULT false;   -- MASTER send gate (= AND of the three sub-flags)
ALTER TABLE leads ADD COLUMN IF NOT EXISTS claude_review_notes  jsonb        DEFAULT '{}'::jsonb;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS claude_reviewed_at   timestamptz;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS claude_review_batch  text;

-- partial index: the safeguard's work-queue (released-but-not-yet-cleared), ordered by release time
CREATE INDEX IF NOT EXISTS idx_leads_claude_uncleared ON leads (governor_released_at) WHERE COALESCE(claude_cleared,false)=false;

-- ── engine_gap_fixes: the gap → root-cause → PR → re-mint ledger (additive engine data) ──
CREATE TABLE IF NOT EXISTS engine_gap_fixes (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_ref       text,
  audit_hash     text,
  domain         text,
  sector         text,
  gap_type       text,                       -- 'law' | 'live_error' | 'competitor' | 'copy'
  gap_detail     jsonb,                       -- the engine-vs-real comparison structure
  root_cause     text,                        -- engine file + symbol Claude identified
  fix_pr_url     text,
  fixture_path   text,                        -- the eval/audit-gaps.json entry that locks it
  status         text DEFAULT 'open',         -- open | pr_open | merged | reminted | verified
  detected_at    timestamptz DEFAULT now(),
  resolved_at    timestamptz,
  detected_batch text
);
CREATE INDEX IF NOT EXISTS idx_engine_gap_fixes_status ON engine_gap_fixes (status);
CREATE INDEX IF NOT EXISTS idx_engine_gap_fixes_hash   ON engine_gap_fixes (audit_hash);

-- ── scraper_daily: per-scraper daily yield (the founder's "~50 Tier-1/day per scraper" tracking) ──
CREATE TABLE IF NOT EXISTS scraper_daily (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scraper_source   text,
  day              date,
  sourced_n        integer DEFAULT 0,
  t1_eligible_n    integer DEFAULT 0,
  valid_email_pct  numeric,
  sector_match_pct numeric,
  cost             numeric,
  recorded_at      timestamptz DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_scraper_daily_source_day ON scraper_daily (scraper_source, day);

-- ── v_scraper_daily: live per-scraper daily counts straight off leads (zero-write lens for the cockpit) ──
CREATE OR REPLACE VIEW v_scraper_daily AS
SELECT
  COALESCE(NULLIF(source,''),'(unknown)')                              AS scraper_source,
  date(COALESCE(scraped_at, imported_at, created_at))                  AS day,
  count(*)                                                             AS sourced_n,
  count(*) FILTER (WHERE icp_tier = 1)                                 AS tier1_n,
  count(*) FILTER (WHERE quality_fit = true)                           AS fit_n,
  round(100.0 * count(*) FILTER (WHERE COALESCE(NULLIF(deliverability,''), verify_status, '') NOT IN
        ('bad','invalid','undeliverable','no_mx','nxdomain','disposable') AND COALESCE(contact_email,email,'') <> '')
        / NULLIF(count(*),0), 1)                                       AS valid_email_pct,
  round(100.0 * count(*) FILTER (WHERE COALESCE(sector_code, sector, '') <> '') / NULLIF(count(*),0), 1) AS sector_match_pct
FROM leads
WHERE COALESCE(scraped_at, imported_at, created_at) IS NOT NULL
GROUP BY 1, 2;

-- read roles (harmless if a role is absent on this DB)
GRANT SELECT ON v_scraper_daily TO tamazia_ro;
GRANT SELECT ON scraper_daily   TO tamazia_ro;
GRANT SELECT ON engine_gap_fixes TO tamazia_ro;
-- GRANT SELECT ON v_scraper_daily TO metabase_ro;   -- uncomment if metabase_ro exists
