-- 130 response templates · 13 categories × 10 sectors.
-- Templates are SHORT (≤200 words target) and use {lead_first_name}, {firm}, {sector}, {pricing_anchor} placeholders.
-- Generated by the response-template generator under src/skills/S013-response-draft-generator.
-- Each category × sector is one row; the body_template is a clean canonical reply.

INSERT INTO response_templates (workspace_id, template_id, category, sector, body_template, subject_template, notes) VALUES
-- HOT_BOOK (recipient wants to book a call) × 10 sectors
(1, 'HOT_BOOK_hospitality', 'HOT_BOOK', 'hospitality', '{lead_first_name}, that is great. The Tamazia scan covers PECR Reg 6, GA4 consent gating, schema completeness, mobile Core Web Vitals and structured-data coverage for {firm}. 45-minute walk-through works well. Pick a slot at cal.com/tamazia/strategy-call — happy to share the prep doc beforehand.', 'Re: {firm} · happy to walk through', 'safe auto-send candidate'),
(1, 'HOT_BOOK_healthcare', 'HOT_BOOK', 'healthcare', '{lead_first_name}, happy to walk through. The scan covers MHRA + CAP Section 12 substantiation, CQC rating display, cookie analytics gating and clinical-claim ASA exposure for {firm}. 45 minutes is enough. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to walk through', 'safe auto-send'),
(1, 'HOT_BOOK_real-estate', 'HOT_BOOK', 'real-estate', '{lead_first_name}, happy to walk through. The scan covers CMA price display, RICS Lettings Code, Tenant Fees Act disclosure, GA4 consent gating and listings-pages schema for {firm}. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to walk through', 'safe auto-send'),
(1, 'HOT_BOOK_law-firms', 'HOT_BOOK', 'law-firms', '{lead_first_name}, happy to walk through. The scan covers SRA Transparency Rules, complaints procedure publication, ICO cookie position, CMA price display and SRA badge placement for {firm}. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to walk through', 'safe auto-send'),
(1, 'HOT_BOOK_finance', 'HOT_BOOK', 'finance', '{lead_first_name}, happy to walk through. The scan covers FCA CONC 2.5 financial-promotion rules, Section 21 approver regime touchpoints, ASA financial-promotion code and ICO cookie position for {firm}. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to walk through', 'safe auto-send'),
(1, 'HOT_BOOK_retail', 'HOT_BOOK', 'retail', '{lead_first_name}, happy to walk through. The scan covers CMA Digital Markets, Competition and Consumers Act disclosure, ASA pricing-clarity, GA4 consent gating and structured-data depth for {firm}. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to walk through', ''),
(1, 'HOT_BOOK_e-commerce', 'HOT_BOOK', 'e-commerce', '{lead_first_name}, happy to walk through. The scan covers Consumer Rights Act + ASA price-display, product-schema completeness, Trustpilot-style review-display rules, GA4 consent gating for {firm}. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to walk through', ''),
(1, 'HOT_BOOK_professional-services', 'HOT_BOOK', 'professional-services', '{lead_first_name}, happy to walk through. The scan covers professional-body rules applicable to {firm} (ICAEW / RICS / CIM / equivalents), ICO cookie position, schema completeness and CWV. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to walk through', ''),
(1, 'HOT_BOOK_manufacturing', 'HOT_BOOK', 'manufacturing', '{lead_first_name}, happy to walk through. The scan covers UKCA/CE marking display, REACH disclosure, ASA performance-claim substantiation, ICO cookie position and B2B Schema for {firm}. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to walk through', ''),
(1, 'HOT_BOOK_education', 'HOT_BOOK', 'education', '{lead_first_name}, happy to walk through. The scan covers OfS / DfE / Ofsted display rules applicable to {firm}, GDPR age-of-consent considerations, ASA education-promotion code and CWV for {firm}. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to walk through', ''),

-- HOT_PRICE (recipient asks about price) × 10
(1, 'HOT_PRICE_hospitality', 'HOT_PRICE', 'hospitality', '{lead_first_name}, the Foundation retainer is £1,500/month, Authority is £3,500, Dominator £7,500. The complimentary Regulatory Signal Scan is delivered before any retainer engagement and the findings are yours to keep regardless. Happy to share the tier comparison sheet — would the 30-min slot at cal.com/tamazia/strategy-call work?', 'Re: {firm} · tier pricing', 'requires Aman approval'),
(1, 'HOT_PRICE_healthcare', 'HOT_PRICE', 'healthcare', '{lead_first_name}, three retainer tiers — Foundation £1,500/month, Authority £3,500, Dominator £7,500. The complimentary Regulatory Signal Scan is always pre-retainer and the findings are yours to keep. Happy to share the tier comparison — cal.com/tamazia/strategy-call.', 'Re: {firm} · tier pricing', 'requires Aman approval'),
(1, 'HOT_PRICE_real-estate', 'HOT_PRICE', 'real-estate', '{lead_first_name}, three tiers — Foundation £1,500/month, Authority £3,500, Dominator £7,500. The scan is pre-retainer and findings yours to keep. Comparison sheet on request — cal.com/tamazia/strategy-call.', 'Re: {firm} · tier pricing', 'requires Aman approval'),
(1, 'HOT_PRICE_law-firms', 'HOT_PRICE', 'law-firms', '{lead_first_name}, three tiers — Foundation £1,500/month, Authority £3,500, Dominator £7,500. The scan is pre-retainer. Comparison sheet on request — cal.com/tamazia/strategy-call.', 'Re: {firm} · tier pricing', 'requires Aman approval'),
(1, 'HOT_PRICE_finance', 'HOT_PRICE', 'finance', '{lead_first_name}, three tiers — Foundation £1,500/month, Authority £3,500, Dominator £7,500. Pre-retainer scan included. cal.com/tamazia/strategy-call.', 'Re: {firm} · tier pricing', 'requires Aman approval'),
(1, 'HOT_PRICE_retail', 'HOT_PRICE', 'retail', '{lead_first_name}, three retainer tiers — £1,500 / £3,500 / £7,500 monthly. Pre-retainer scan included. Comparison on request — cal.com/tamazia/strategy-call.', 'Re: {firm} · tier pricing', ''),
(1, 'HOT_PRICE_e-commerce', 'HOT_PRICE', 'e-commerce', '{lead_first_name}, three tiers — £1,500 / £3,500 / £7,500 monthly. Pre-retainer scan included. cal.com/tamazia/strategy-call.', 'Re: {firm} · tier pricing', ''),
(1, 'HOT_PRICE_professional-services', 'HOT_PRICE', 'professional-services', '{lead_first_name}, three tiers — £1,500 / £3,500 / £7,500 monthly. Pre-retainer scan included. cal.com/tamazia/strategy-call.', 'Re: {firm} · tier pricing', ''),
(1, 'HOT_PRICE_manufacturing', 'HOT_PRICE', 'manufacturing', '{lead_first_name}, three tiers — £1,500 / £3,500 / £7,500 monthly. Pre-retainer scan included. cal.com/tamazia/strategy-call.', 'Re: {firm} · tier pricing', ''),
(1, 'HOT_PRICE_education', 'HOT_PRICE', 'education', '{lead_first_name}, three tiers — £1,500 / £3,500 / £7,500 monthly. Pre-retainer scan included. cal.com/tamazia/strategy-call.', 'Re: {firm} · tier pricing', ''),

-- WARM_INFO (recipient wants more information before booking) × 10
(1, 'WARM_INFO_hospitality', 'WARM_INFO', 'hospitality', '{lead_first_name}, share the diagnostic for {firm} below. The complimentary Regulatory Signal Scan covers 21 checks across PECR, GA4 consent, schema, Core Web Vitals, mobile UX and trust signals. Output is a hosted page plus a PDF, findings yours to keep. Open to a 30-min walk-through at cal.com/tamazia/strategy-call if useful.', 'Re: {firm} · scan breakdown', 'safe auto-send'),
(1, 'WARM_INFO_healthcare', 'WARM_INFO', 'healthcare', '{lead_first_name}, share the scan breakdown for {firm} below. 21 checks across MHRA, CAP Section 12, CQC, ICO cookies, schema, CWV, mobile, trust signals. Output: hosted page + PDF, findings yours to keep. cal.com/tamazia/strategy-call.', 'Re: {firm} · scan breakdown', 'safe auto-send'),
(1, 'WARM_INFO_real-estate', 'WARM_INFO', 'real-estate', '{lead_first_name}, scan breakdown for {firm} below. 21 checks across CMA, RICS, Tenant Fees, ICO cookies, listings-schema, CWV. Output: hosted + PDF. cal.com/tamazia/strategy-call.', 'Re: {firm} · scan breakdown', 'safe auto-send'),
(1, 'WARM_INFO_law-firms', 'WARM_INFO', 'law-firms', '{lead_first_name}, scan breakdown for {firm} below. 21 checks across SRA Transparency, complaints procedure, ICO cookies, CMA price display, schema. Output: hosted + PDF. cal.com/tamazia/strategy-call.', 'Re: {firm} · scan breakdown', 'safe auto-send'),
(1, 'WARM_INFO_finance', 'WARM_INFO', 'finance', '{lead_first_name}, scan breakdown for {firm} below. 21 checks across FCA CONC 2.5, Section 21 approver regime, ASA financial-promotion code, ICO cookies. Output: hosted + PDF. cal.com/tamazia/strategy-call.', 'Re: {firm} · scan breakdown', 'safe auto-send'),
(1, 'WARM_INFO_retail', 'WARM_INFO', 'retail', '{lead_first_name}, scan breakdown for {firm} below. 21 checks across CMA Digital Markets, ASA pricing-clarity, ICO cookies, product schema. Hosted + PDF. cal.com/tamazia/strategy-call.', 'Re: {firm} · scan breakdown', ''),
(1, 'WARM_INFO_e-commerce', 'WARM_INFO', 'e-commerce', '{lead_first_name}, scan breakdown for {firm} below. 21 checks across Consumer Rights Act, ASA price display, product schema, review display rules. Hosted + PDF. cal.com/tamazia/strategy-call.', 'Re: {firm} · scan breakdown', ''),
(1, 'WARM_INFO_professional-services', 'WARM_INFO', 'professional-services', '{lead_first_name}, scan breakdown for {firm} below. 21 checks across professional-body rules for {sector}, ICO cookies, schema. cal.com/tamazia/strategy-call.', 'Re: {firm} · scan breakdown', ''),
(1, 'WARM_INFO_manufacturing', 'WARM_INFO', 'manufacturing', '{lead_first_name}, scan breakdown for {firm} below. 21 checks across UKCA, REACH disclosure, ASA performance claims, ICO cookies, B2B schema. cal.com/tamazia/strategy-call.', 'Re: {firm} · scan breakdown', ''),
(1, 'WARM_INFO_education', 'WARM_INFO', 'education', '{lead_first_name}, scan breakdown for {firm} below. 21 checks across OfS / DfE / Ofsted rules, GDPR considerations, ASA education-promotion code, schema. cal.com/tamazia/strategy-call.', 'Re: {firm} · scan breakdown', ''),

-- WARM_TIMING (recipient says "not now, later") × 10
(1, 'WARM_TIMING_hospitality', 'WARM_TIMING', 'hospitality', '{lead_first_name}, understood. I will set a soft reminder for six weeks out and send the scan brief for {firm} then. If anything urgent surfaces on PECR Reg 6 or the GA4 consent position before then, I will flag it. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to wait', ''),
(1, 'WARM_TIMING_healthcare', 'WARM_TIMING', 'healthcare', '{lead_first_name}, understood. I will set a soft reminder for six weeks out and send the scan brief for {firm} then. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to wait', ''),
(1, 'WARM_TIMING_real-estate', 'WARM_TIMING', 'real-estate', '{lead_first_name}, understood. Six-week soft reminder set. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to wait', ''),
(1, 'WARM_TIMING_law-firms', 'WARM_TIMING', 'law-firms', '{lead_first_name}, understood. Six-week soft reminder set. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to wait', ''),
(1, 'WARM_TIMING_finance', 'WARM_TIMING', 'finance', '{lead_first_name}, understood. Six-week soft reminder set. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to wait', ''),
(1, 'WARM_TIMING_retail', 'WARM_TIMING', 'retail', '{lead_first_name}, understood. Six-week soft reminder set. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to wait', ''),
(1, 'WARM_TIMING_e-commerce', 'WARM_TIMING', 'e-commerce', '{lead_first_name}, understood. Six-week soft reminder set. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to wait', ''),
(1, 'WARM_TIMING_professional-services', 'WARM_TIMING', 'professional-services', '{lead_first_name}, understood. Six-week soft reminder set. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to wait', ''),
(1, 'WARM_TIMING_manufacturing', 'WARM_TIMING', 'manufacturing', '{lead_first_name}, understood. Six-week soft reminder set. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to wait', ''),
(1, 'WARM_TIMING_education', 'WARM_TIMING', 'education', '{lead_first_name}, understood. Six-week soft reminder set. cal.com/tamazia/strategy-call.', 'Re: {firm} · happy to wait', ''),

-- NURTURE (interested, no immediate action, keep relationship warm) × 10
(1, 'NURTURE_hospitality', 'NURTURE', 'hospitality', '{lead_first_name}, appreciate the note. I will keep {firm} on the watch list for sector-relevant signals on PECR + ICO cookie + ASA hospitality angle and share if anything material shifts. No follow-up otherwise.', 'Re: {firm} · noted', ''),
(1, 'NURTURE_healthcare', 'NURTURE', 'healthcare', '{lead_first_name}, appreciate the note. I will keep {firm} on the watch list for MHRA / CAP 12 / ICO cookie shifts and share material updates. No follow-up otherwise.', 'Re: {firm} · noted', ''),
(1, 'NURTURE_real-estate', 'NURTURE', 'real-estate', '{lead_first_name}, appreciate the note. {firm} on the watch list for CMA / RICS / ICO cookie shifts. No follow-up otherwise.', 'Re: {firm} · noted', ''),
(1, 'NURTURE_law-firms', 'NURTURE', 'law-firms', '{lead_first_name}, appreciate the note. {firm} on the watch list for SRA / ICO cookie shifts. No follow-up otherwise.', 'Re: {firm} · noted', ''),
(1, 'NURTURE_finance', 'NURTURE', 'finance', '{lead_first_name}, appreciate the note. {firm} on the watch list for FCA CONC 2.5 / Section 21 / ASA finance code shifts. No follow-up otherwise.', 'Re: {firm} · noted', ''),
(1, 'NURTURE_retail', 'NURTURE', 'retail', '{lead_first_name}, appreciate the note. {firm} on the watch list for CMA / ASA / ICO cookie shifts. No follow-up otherwise.', 'Re: {firm} · noted', ''),
(1, 'NURTURE_e-commerce', 'NURTURE', 'e-commerce', '{lead_first_name}, appreciate the note. {firm} on the watch list for CRA / ASA / ICO cookie shifts. No follow-up otherwise.', 'Re: {firm} · noted', ''),
(1, 'NURTURE_professional-services', 'NURTURE', 'professional-services', '{lead_first_name}, appreciate the note. {firm} on the watch list for professional-body code shifts. No follow-up otherwise.', 'Re: {firm} · noted', ''),
(1, 'NURTURE_manufacturing', 'NURTURE', 'manufacturing', '{lead_first_name}, appreciate the note. {firm} on the watch list for UKCA / REACH / ASA shifts. No follow-up otherwise.', 'Re: {firm} · noted', ''),
(1, 'NURTURE_education', 'NURTURE', 'education', '{lead_first_name}, appreciate the note. {firm} on the watch list for OfS / DfE / Ofsted / ASA shifts. No follow-up otherwise.', 'Re: {firm} · noted', ''),

-- OBJECTION_BUDGET × 10
(1, 'OBJECTION_BUDGET_hospitality', 'OBJECTION_BUDGET', 'hospitality', '{lead_first_name}, fair. Foundation at £1,500/month is the entry point; the complimentary Regulatory Signal Scan remains pre-retainer and findings are yours to keep without commitment. Happy to share the scan first, retainer conversation later if relevant. cal.com/tamazia/strategy-call.', 'Re: {firm} · understand on budget', 'requires Aman approval'),
(1, 'OBJECTION_BUDGET_healthcare', 'OBJECTION_BUDGET', 'healthcare', '{lead_first_name}, fair. Pre-retainer scan stands regardless; findings yours to keep. cal.com/tamazia/strategy-call.', 'Re: {firm} · understand on budget', 'requires Aman approval'),
(1, 'OBJECTION_BUDGET_real-estate', 'OBJECTION_BUDGET', 'real-estate', '{lead_first_name}, fair. Pre-retainer scan stands; findings yours to keep. cal.com/tamazia/strategy-call.', 'Re: {firm} · understand on budget', 'requires Aman approval'),
(1, 'OBJECTION_BUDGET_law-firms', 'OBJECTION_BUDGET', 'law-firms', '{lead_first_name}, fair. Pre-retainer scan stands; findings yours to keep. cal.com/tamazia/strategy-call.', 'Re: {firm} · understand on budget', 'requires Aman approval'),
(1, 'OBJECTION_BUDGET_finance', 'OBJECTION_BUDGET', 'finance', '{lead_first_name}, fair. Pre-retainer scan stands; findings yours to keep. cal.com/tamazia/strategy-call.', 'Re: {firm} · understand on budget', 'requires Aman approval'),
(1, 'OBJECTION_BUDGET_retail', 'OBJECTION_BUDGET', 'retail', '{lead_first_name}, fair. Pre-retainer scan stands; findings yours to keep. cal.com/tamazia/strategy-call.', 'Re: {firm} · understand on budget', ''),
(1, 'OBJECTION_BUDGET_e-commerce', 'OBJECTION_BUDGET', 'e-commerce', '{lead_first_name}, fair. Pre-retainer scan stands; findings yours to keep. cal.com/tamazia/strategy-call.', 'Re: {firm} · understand on budget', ''),
(1, 'OBJECTION_BUDGET_professional-services', 'OBJECTION_BUDGET', 'professional-services', '{lead_first_name}, fair. Pre-retainer scan stands; findings yours to keep. cal.com/tamazia/strategy-call.', 'Re: {firm} · understand on budget', ''),
(1, 'OBJECTION_BUDGET_manufacturing', 'OBJECTION_BUDGET', 'manufacturing', '{lead_first_name}, fair. Pre-retainer scan stands; findings yours to keep. cal.com/tamazia/strategy-call.', 'Re: {firm} · understand on budget', ''),
(1, 'OBJECTION_BUDGET_education', 'OBJECTION_BUDGET', 'education', '{lead_first_name}, fair. Pre-retainer scan stands; findings yours to keep. cal.com/tamazia/strategy-call.', 'Re: {firm} · understand on budget', ''),

-- OBJECTION_INCUMBENT × 10
(1, 'OBJECTION_INCUMBENT_hospitality', 'OBJECTION_INCUMBENT', 'hospitality', '{lead_first_name}, fair — most decent agencies handle the technical SEO ground. Tamazia adds the regulatory layer (PECR Reg 6, ASA, ICO 2024 position) that 80% of growth-only agencies miss. The complimentary scan would show {firm} exactly what is and is not being covered today, no obligation. cal.com/tamazia/strategy-call.', 'Re: {firm} · re: existing agency', 'requires Aman approval'),
(1, 'OBJECTION_INCUMBENT_healthcare', 'OBJECTION_INCUMBENT', 'healthcare', '{lead_first_name}, fair. Tamazia adds the regulatory layer (MHRA / CAP 12 / CQC / ASA) that most growth agencies miss. The complimentary scan would show {firm} exactly what is and is not being covered today. cal.com/tamazia/strategy-call.', 'Re: {firm} · re: existing agency', 'requires Aman approval'),
(1, 'OBJECTION_INCUMBENT_real-estate', 'OBJECTION_INCUMBENT', 'real-estate', '{lead_first_name}, fair. Tamazia adds CMA / RICS / Tenant Fees Act layer most agencies miss. Complimentary scan would show {firm} what is and is not covered today. cal.com/tamazia/strategy-call.', 'Re: {firm} · re: existing agency', 'requires Aman approval'),
(1, 'OBJECTION_INCUMBENT_law-firms', 'OBJECTION_INCUMBENT', 'law-firms', '{lead_first_name}, fair. Tamazia adds the SRA / CMA / ICO layer that most agencies miss. Complimentary scan would show {firm} the gaps. cal.com/tamazia/strategy-call.', 'Re: {firm} · re: existing agency', 'requires Aman approval'),
(1, 'OBJECTION_INCUMBENT_finance', 'OBJECTION_INCUMBENT', 'finance', '{lead_first_name}, fair. Tamazia adds the FCA CONC / Section 21 / ASA layer most agencies miss. Complimentary scan would show {firm} the gaps. cal.com/tamazia/strategy-call.', 'Re: {firm} · re: existing agency', 'requires Aman approval'),
(1, 'OBJECTION_INCUMBENT_retail', 'OBJECTION_INCUMBENT', 'retail', '{lead_first_name}, fair. Tamazia adds CMA / ASA / consumer-protection layer most agencies miss. cal.com/tamazia/strategy-call.', 'Re: {firm} · re: existing agency', ''),
(1, 'OBJECTION_INCUMBENT_e-commerce', 'OBJECTION_INCUMBENT', 'e-commerce', '{lead_first_name}, fair. Tamazia adds CRA / ASA / consumer-protection layer most agencies miss. cal.com/tamazia/strategy-call.', 'Re: {firm} · re: existing agency', ''),
(1, 'OBJECTION_INCUMBENT_professional-services', 'OBJECTION_INCUMBENT', 'professional-services', '{lead_first_name}, fair. Tamazia adds the professional-body code layer most agencies miss. cal.com/tamazia/strategy-call.', 'Re: {firm} · re: existing agency', ''),
(1, 'OBJECTION_INCUMBENT_manufacturing', 'OBJECTION_INCUMBENT', 'manufacturing', '{lead_first_name}, fair. Tamazia adds UKCA / REACH / ASA layer most agencies miss. cal.com/tamazia/strategy-call.', 'Re: {firm} · re: existing agency', ''),
(1, 'OBJECTION_INCUMBENT_education', 'OBJECTION_INCUMBENT', 'education', '{lead_first_name}, fair. Tamazia adds OfS / DfE / Ofsted / ASA layer most agencies miss. cal.com/tamazia/strategy-call.', 'Re: {firm} · re: existing agency', ''),

-- OBJECTION_FIT (recipient says wrong fit, wrong product) × 10
(1, 'OBJECTION_FIT_hospitality', 'OBJECTION_FIT', 'hospitality', '{lead_first_name}, understood — appreciate the directness. If the picture changes at {firm} or someone in your network is rebuilding compliance-aware SEO, the door is open. No further follow-up from me on this thread.', 'Re: {firm} · understood', 'safe auto-send'),
(1, 'OBJECTION_FIT_healthcare', 'OBJECTION_FIT', 'healthcare', '{lead_first_name}, understood. Door open if it changes. No further follow-up.', 'Re: {firm} · understood', 'safe auto-send'),
(1, 'OBJECTION_FIT_real-estate', 'OBJECTION_FIT', 'real-estate', '{lead_first_name}, understood. Door open if it changes. No further follow-up.', 'Re: {firm} · understood', 'safe auto-send'),
(1, 'OBJECTION_FIT_law-firms', 'OBJECTION_FIT', 'law-firms', '{lead_first_name}, understood. Door open if it changes. No further follow-up.', 'Re: {firm} · understood', 'safe auto-send'),
(1, 'OBJECTION_FIT_finance', 'OBJECTION_FIT', 'finance', '{lead_first_name}, understood. Door open if it changes. No further follow-up.', 'Re: {firm} · understood', 'safe auto-send'),
(1, 'OBJECTION_FIT_retail', 'OBJECTION_FIT', 'retail', '{lead_first_name}, understood. Door open if it changes. No further follow-up.', 'Re: {firm} · understood', ''),
(1, 'OBJECTION_FIT_e-commerce', 'OBJECTION_FIT', 'e-commerce', '{lead_first_name}, understood. Door open if it changes. No further follow-up.', 'Re: {firm} · understood', ''),
(1, 'OBJECTION_FIT_professional-services', 'OBJECTION_FIT', 'professional-services', '{lead_first_name}, understood. Door open if it changes. No further follow-up.', 'Re: {firm} · understood', ''),
(1, 'OBJECTION_FIT_manufacturing', 'OBJECTION_FIT', 'manufacturing', '{lead_first_name}, understood. Door open if it changes. No further follow-up.', 'Re: {firm} · understood', ''),
(1, 'OBJECTION_FIT_education', 'OBJECTION_FIT', 'education', '{lead_first_name}, understood. Door open if it changes. No further follow-up.', 'Re: {firm} · understood', ''),

-- REDIRECT (recipient hands off to colleague) × 10
(1, 'REDIRECT_hospitality', 'REDIRECT', 'hospitality', '{lead_first_name}, appreciate the redirect. I will reach out to the named colleague with the same observation tailored to their remit and copy you in case useful.', 'Re: {firm} · happy to redirect', 'requires Aman approval'),
(1, 'REDIRECT_healthcare', 'REDIRECT', 'healthcare', '{lead_first_name}, appreciate the redirect. Will reach out to the named colleague and copy you.', 'Re: {firm} · happy to redirect', 'requires Aman approval'),
(1, 'REDIRECT_real-estate', 'REDIRECT', 'real-estate', '{lead_first_name}, appreciate the redirect. Will reach out to the named colleague and copy you.', 'Re: {firm} · happy to redirect', 'requires Aman approval'),
(1, 'REDIRECT_law-firms', 'REDIRECT', 'law-firms', '{lead_first_name}, appreciate the redirect. Will reach out to the named colleague and copy you.', 'Re: {firm} · happy to redirect', 'requires Aman approval'),
(1, 'REDIRECT_finance', 'REDIRECT', 'finance', '{lead_first_name}, appreciate the redirect. Will reach out to the named colleague and copy you.', 'Re: {firm} · happy to redirect', 'requires Aman approval'),
(1, 'REDIRECT_retail', 'REDIRECT', 'retail', '{lead_first_name}, appreciate the redirect. Will reach out to the named colleague.', 'Re: {firm} · happy to redirect', ''),
(1, 'REDIRECT_e-commerce', 'REDIRECT', 'e-commerce', '{lead_first_name}, appreciate the redirect. Will reach out to the named colleague.', 'Re: {firm} · happy to redirect', ''),
(1, 'REDIRECT_professional-services', 'REDIRECT', 'professional-services', '{lead_first_name}, appreciate the redirect. Will reach out to the named colleague.', 'Re: {firm} · happy to redirect', ''),
(1, 'REDIRECT_manufacturing', 'REDIRECT', 'manufacturing', '{lead_first_name}, appreciate the redirect. Will reach out to the named colleague.', 'Re: {firm} · happy to redirect', ''),
(1, 'REDIRECT_education', 'REDIRECT', 'education', '{lead_first_name}, appreciate the redirect. Will reach out to the named colleague.', 'Re: {firm} · happy to redirect', ''),

-- OOO (out of office auto-reply) × 10  -- never auto-respond to OOO; lead stays in sequence
(1, 'OOO_hospitality', 'OOO', 'hospitality', 'NO_REPLY', 'NO_REPLY', 'OOO: do not respond; lead.replied stays FALSE; wait for human reply'),
(1, 'OOO_healthcare', 'OOO', 'healthcare', 'NO_REPLY', 'NO_REPLY', 'OOO: do not respond'),
(1, 'OOO_real-estate', 'OOO', 'real-estate', 'NO_REPLY', 'NO_REPLY', 'OOO: do not respond'),
(1, 'OOO_law-firms', 'OOO', 'law-firms', 'NO_REPLY', 'NO_REPLY', 'OOO: do not respond'),
(1, 'OOO_finance', 'OOO', 'finance', 'NO_REPLY', 'NO_REPLY', 'OOO: do not respond'),
(1, 'OOO_retail', 'OOO', 'retail', 'NO_REPLY', 'NO_REPLY', 'OOO: do not respond'),
(1, 'OOO_e-commerce', 'OOO', 'e-commerce', 'NO_REPLY', 'NO_REPLY', 'OOO: do not respond'),
(1, 'OOO_professional-services', 'OOO', 'professional-services', 'NO_REPLY', 'NO_REPLY', 'OOO: do not respond'),
(1, 'OOO_manufacturing', 'OOO', 'manufacturing', 'NO_REPLY', 'NO_REPLY', 'OOO: do not respond'),
(1, 'OOO_education', 'OOO', 'education', 'NO_REPLY', 'NO_REPLY', 'OOO: do not respond'),

-- HOSTILE × 10
(1, 'HOSTILE_hospitality', 'HOSTILE', 'hospitality', 'MANUAL_REVIEW_AMAN', 'MANUAL_REVIEW_AMAN', 'route to Aman with Telegram P0; never auto-send'),
(1, 'HOSTILE_healthcare', 'HOSTILE', 'healthcare', 'MANUAL_REVIEW_AMAN', 'MANUAL_REVIEW_AMAN', 'route to Aman'),
(1, 'HOSTILE_real-estate', 'HOSTILE', 'real-estate', 'MANUAL_REVIEW_AMAN', 'MANUAL_REVIEW_AMAN', 'route to Aman'),
(1, 'HOSTILE_law-firms', 'HOSTILE', 'law-firms', 'MANUAL_REVIEW_AMAN', 'MANUAL_REVIEW_AMAN', 'route to Aman'),
(1, 'HOSTILE_finance', 'HOSTILE', 'finance', 'MANUAL_REVIEW_AMAN', 'MANUAL_REVIEW_AMAN', 'route to Aman'),
(1, 'HOSTILE_retail', 'HOSTILE', 'retail', 'MANUAL_REVIEW_AMAN', 'MANUAL_REVIEW_AMAN', 'route to Aman'),
(1, 'HOSTILE_e-commerce', 'HOSTILE', 'e-commerce', 'MANUAL_REVIEW_AMAN', 'MANUAL_REVIEW_AMAN', 'route to Aman'),
(1, 'HOSTILE_professional-services', 'HOSTILE', 'professional-services', 'MANUAL_REVIEW_AMAN', 'MANUAL_REVIEW_AMAN', 'route to Aman'),
(1, 'HOSTILE_manufacturing', 'HOSTILE', 'manufacturing', 'MANUAL_REVIEW_AMAN', 'MANUAL_REVIEW_AMAN', 'route to Aman'),
(1, 'HOSTILE_education', 'HOSTILE', 'education', 'MANUAL_REVIEW_AMAN', 'MANUAL_REVIEW_AMAN', 'route to Aman'),

-- LEGAL_THREAT × 10
(1, 'LEGAL_THREAT_hospitality', 'LEGAL_THREAT', 'hospitality', 'MANUAL_REVIEW_DANISH', 'MANUAL_REVIEW_DANISH', 'route to Aman + Danish (CLO) with Telegram P0; never auto-send; immediate suppression via DNC; preserve original message for legal record'),
(1, 'LEGAL_THREAT_healthcare', 'LEGAL_THREAT', 'healthcare', 'MANUAL_REVIEW_DANISH', 'MANUAL_REVIEW_DANISH', 'legal route'),
(1, 'LEGAL_THREAT_real-estate', 'LEGAL_THREAT', 'real-estate', 'MANUAL_REVIEW_DANISH', 'MANUAL_REVIEW_DANISH', 'legal route'),
(1, 'LEGAL_THREAT_law-firms', 'LEGAL_THREAT', 'law-firms', 'MANUAL_REVIEW_DANISH', 'MANUAL_REVIEW_DANISH', 'legal route'),
(1, 'LEGAL_THREAT_finance', 'LEGAL_THREAT', 'finance', 'MANUAL_REVIEW_DANISH', 'MANUAL_REVIEW_DANISH', 'legal route'),
(1, 'LEGAL_THREAT_retail', 'LEGAL_THREAT', 'retail', 'MANUAL_REVIEW_DANISH', 'MANUAL_REVIEW_DANISH', 'legal route'),
(1, 'LEGAL_THREAT_e-commerce', 'LEGAL_THREAT', 'e-commerce', 'MANUAL_REVIEW_DANISH', 'MANUAL_REVIEW_DANISH', 'legal route'),
(1, 'LEGAL_THREAT_professional-services', 'LEGAL_THREAT', 'professional-services', 'MANUAL_REVIEW_DANISH', 'MANUAL_REVIEW_DANISH', 'legal route'),
(1, 'LEGAL_THREAT_manufacturing', 'LEGAL_THREAT', 'manufacturing', 'MANUAL_REVIEW_DANISH', 'MANUAL_REVIEW_DANISH', 'legal route'),
(1, 'LEGAL_THREAT_education', 'LEGAL_THREAT', 'education', 'MANUAL_REVIEW_DANISH', 'MANUAL_REVIEW_DANISH', 'legal route'),

-- UNSUBSCRIBE × 10
(1, 'UNSUBSCRIBE_hospitality', 'UNSUBSCRIBE', 'hospitality', '{lead_first_name}, removed and noted. No further outreach from Tamazia.', 'Re: {firm} · removed', 'safe auto-send; immediate DNC enrolment'),
(1, 'UNSUBSCRIBE_healthcare', 'UNSUBSCRIBE', 'healthcare', '{lead_first_name}, removed and noted. No further outreach from Tamazia.', 'Re: {firm} · removed', 'safe auto-send + DNC'),
(1, 'UNSUBSCRIBE_real-estate', 'UNSUBSCRIBE', 'real-estate', '{lead_first_name}, removed and noted. No further outreach from Tamazia.', 'Re: {firm} · removed', 'safe auto-send + DNC'),
(1, 'UNSUBSCRIBE_law-firms', 'UNSUBSCRIBE', 'law-firms', '{lead_first_name}, removed and noted. No further outreach from Tamazia.', 'Re: {firm} · removed', 'safe auto-send + DNC'),
(1, 'UNSUBSCRIBE_finance', 'UNSUBSCRIBE', 'finance', '{lead_first_name}, removed and noted. No further outreach from Tamazia.', 'Re: {firm} · removed', 'safe auto-send + DNC'),
(1, 'UNSUBSCRIBE_retail', 'UNSUBSCRIBE', 'retail', '{lead_first_name}, removed and noted. No further outreach from Tamazia.', 'Re: {firm} · removed', 'safe auto-send + DNC'),
(1, 'UNSUBSCRIBE_e-commerce', 'UNSUBSCRIBE', 'e-commerce', '{lead_first_name}, removed and noted. No further outreach from Tamazia.', 'Re: {firm} · removed', 'safe auto-send + DNC'),
(1, 'UNSUBSCRIBE_professional-services', 'UNSUBSCRIBE', 'professional-services', '{lead_first_name}, removed and noted. No further outreach from Tamazia.', 'Re: {firm} · removed', 'safe auto-send + DNC'),
(1, 'UNSUBSCRIBE_manufacturing', 'UNSUBSCRIBE', 'manufacturing', '{lead_first_name}, removed and noted. No further outreach from Tamazia.', 'Re: {firm} · removed', 'safe auto-send + DNC'),
(1, 'UNSUBSCRIBE_education', 'UNSUBSCRIBE', 'education', '{lead_first_name}, removed and noted. No further outreach from Tamazia.', 'Re: {firm} · removed', 'safe auto-send + DNC')
ON CONFLICT (workspace_id, template_id) DO NOTHING;
