-- 50 warmup conversation pairs across 6 categories (4.1.2).
-- Used by W1b warmup engine to drive alias-to-alias replies that look like real B2B traffic.
-- Categories: project_update, q_and_a, scheduling, deliverable_handoff, status_report, casual_acknowledgement.

INSERT INTO warmup_pairs (category, subject, body, reply_subject, reply_body) VALUES
  -- project_update (10)
  ('project_update','Q2 report status','Hi there, quick status on the Q2 report. Sections 1 through 4 are drafted; section 5 (forecasts) is waiting on the latest figures. Aiming to share a full draft by EOD Thursday. Anything you want me to add?','Re: Q2 report status','Thanks for the update. Section 5 will be tight given the deadlines but it sounds workable. Add the regional split on page 3 if you can. Otherwise looks on track.'),
  ('project_update','Sprint 14 wrap-up','Sprint 14 closed yesterday. Two stories carried over, one fully done. The carryover items are unblocked and slotted into sprint 15. Velocity stable. Retrospective notes attached for context.','Re: Sprint 14 wrap-up','Good summary. The carryover pattern is worth watching across the next two sprints. Otherwise solid.'),
  ('project_update','Onboarding milestone reached','Just hit the 30-day milestone with the new account. KPI dashboard is now live and the client has confirmed visibility into the daily metrics. Next milestone is the 60-day review where we look at the early signals.','Re: Onboarding milestone reached','Great news. Make sure the dashboard tracks the leading indicator they cared about most. Let me know how the 60-day review goes.'),
  ('project_update','Migration progress','Phase one of the migration is complete. Schema is in place and historical data has been backfilled. Phase two (live cutover) is scheduled for Saturday night. Rollback path tested.','Re: Migration progress','Good. The rollback path being tested makes me much more comfortable. Stay close to the on-call rota on Saturday in case anything wobbles.'),
  ('project_update','Q3 planning kickoff','Q3 planning starts next week. Pre-read goes out Monday. Draft objectives are ready for review and I would value your input on the customer-success workstream before circulation.','Re: Q3 planning kickoff','Send the pre-read across when you can. I will block 30 minutes before the kickoff to read it properly.'),
  ('project_update','Customer feedback wave','Latest wave of customer interviews is in. Three themes emerged: onboarding friction, reporting depth, and integration coverage. Detailed notes in the shared folder.','Re: Customer feedback wave','The reporting depth point matches what I heard last week from a different segment. Worth surfacing in the planning doc.'),
  ('project_update','Refactor PR landed','The refactor PR landed this morning. CI is green and the staging deploy looks healthy. Will leave it baking on staging for 24 hours before promoting to production.','Re: Refactor PR landed','Sensible. Let me know if anything surfaces in the 24 hour bake.'),
  ('project_update','Pricing experiment results','Pricing experiment closed at 14 days. Variant B outperformed control by 11 percent on conversion with no detectable drop in retention. Recommending we adopt B as the default for new signups.','Re: Pricing experiment results','11 percent is a clean win. Confirm the segments where the effect was strongest before rolling site-wide.'),
  ('project_update','Security review handoff','Internal security review completed. Three medium findings, one low. All have remediation owners and target dates. Full report attached.','Re: Security review handoff','Thanks. Medium findings need owner sign-off; please make sure the dates are realistic.'),
  ('project_update','Content calendar refresh','Refreshed the content calendar for the next six weeks. Two pieces per week, balanced across thought leadership and product-led. First piece publishes Tuesday.','Re: Content calendar refresh','Looks balanced. Make sure the product-led pieces have a clear CTA and tracking on the link.'),

  -- q_and_a (10)
  ('q_and_a','Quick question on the API rate limits','Hi, brief question. The API rate limit page says 60 per minute per key. Is that a hard ceiling or is there headroom for short bursts? We are seeing one 429 every couple of hours on a single integration.','Re: Quick question on the API rate limits','60 per minute is the hard ceiling but short bursts up to 90 in any 60 second window will not be rejected. Anything beyond that returns 429. The integration may be running cleanup jobs in tight loops.'),
  ('q_and_a','Compliance scope clarification','Need to confirm the compliance scope for the next audit. Is the in-house data lake in scope, or only the customer-facing systems? Auditors are asking for a clear answer.','Re: Compliance scope clarification','Customer-facing systems for SOC 2; data lake is in scope only if customer data flows through it. Confirm with engineering before answering.'),
  ('q_and_a','Naming convention check','Quick check on naming. Do we prefer snake_case or kebab-case for new event names in the analytics pipeline? Want to be consistent before I push tomorrow.','Re: Naming convention check','snake_case for events, kebab-case for property keys we expose externally. Internal-only keys can stay snake_case.'),
  ('q_and_a','Storage tier choice','For the new attachment store should I use the standard tier or the infrequent-access tier? Average access is once per attachment in the first month then nothing.','Re: Storage tier choice','Infrequent access fits the pattern. Just confirm the retrieval cost over 12 months is below the standard-tier savings; usually is.'),
  ('q_and_a','Deprecation timeline','Customer asked when v1 of the API will be deprecated. Do we have a public timeline yet?','Re: Deprecation timeline','We committed to 12 months notice. Internal target is Q4 next year. I would not put a hard date in the public docs yet.'),
  ('q_and_a','Branching strategy','Should the new module live on a feature branch or behind a flag on main? Both work but want to align with the team norm.','Re: Branching strategy','Flag on main. Long-running feature branches always drift and the merge pain is not worth it for this size of change.'),
  ('q_and_a','Reporting cadence','Are weekly reports still the cadence or have we moved to biweekly? I keep getting asked.','Re: Reporting cadence','Weekly for now; will revisit at the next planning cycle. The signal-to-noise was better at weekly so we kept it.'),
  ('q_and_a','Database backup retention','How long do we keep the daily database backups? Compliance asked.','Re: Database backup retention','30 days rolling, plus a weekly snapshot at 90 days, plus a monthly snapshot at 12 months. Documented in the runbook.'),
  ('q_and_a','Permission boundary','Does the customer-success team need read access to the billing schema or only the summary view? Want to scope the new role tightly.','Re: Permission boundary','Summary view only. They have not needed schema-level access historically and there is no reason to broaden it now.'),
  ('q_and_a','Onboarding survey wording','One quick check. In the onboarding survey, should question 4 ask about role or about department? Different teams want different cuts.','Re: Onboarding survey wording','Role. Department is too coarse and changes with re-orgs. We can derive department from role.'),

  -- scheduling (8)
  ('scheduling','Diary check for Thursday','Hi there. Are you free Thursday for a 30-minute walk-through on the new dashboard? Anytime between 10 and 4 works on my end.','Re: Diary check for Thursday','Thursday at 11 works well. Send a calendar invite when convenient. Will dial in from the home office.'),
  ('scheduling','Weekly sync time','Are you happy keeping the weekly sync at Wednesday 10 or shall we move it? I can do Tuesday 4 or Thursday 9 if either works better.','Re: Weekly sync time','Wednesday 10 stays. The midweek rhythm is good and the other slots overlap other commitments.'),
  ('scheduling','Quarterly review date','Pencil in 14th for the quarterly review? Two hours, plus prep on the day before. I will share the agenda once we agree the date.','Re: Quarterly review date','14th works. Send the agenda by the 11th so I can review over the weekend.'),
  ('scheduling','Half-day workshop','Considering a half-day workshop on the new methodology, week of 22nd. Tuesday or Thursday afternoon are the options. Which works?','Re: Half-day workshop','Thursday afternoon. I have a hard stop at 5 but four hours from 1 is comfortable.'),
  ('scheduling','Off-site planning','We are floating an off-site for early next quarter. Two days, somewhere reasonably close to London. Any strong preference on location?','Re: Off-site planning','No strong preference on location. Two days works as long as it does not collide with the quarter close. Brighton or Oxford would both be fine.'),
  ('scheduling','Coffee catch-up','Are you in the office on Friday? Was going to grab a coffee around 11 if you are around.','Re: Coffee catch-up','In on Friday. 11 at the usual place works. See you then.'),
  ('scheduling','Interview slot','We have a strong candidate for the senior role. Friday at 2 for the technical round. Can you take 30 minutes of it?','Re: Interview slot','Friday at 2 to 2:30 works. Share the CV beforehand if possible.'),
  ('scheduling','Diary block for deep work','Will be heads-down on the strategy doc Thursday and Friday morning. Pinging now so calendars line up. Will resurface Friday afternoon.','Re: Diary block for deep work','Noted. Nothing urgent on my side. Catch up Friday afternoon.'),

  -- deliverable_handoff (8)
  ('deliverable_handoff','Draft attached for review','Draft of the strategy memo is attached. Three sections, with the decision matrix on page 4. Looking for directional feedback rather than wordsmithing.','Re: Draft attached for review','Read it. Section 2 framing is the right one. The decision matrix needs a clear recommendation in bold at the top; currently the reader has to assemble it.'),
  ('deliverable_handoff','Slides for tomorrow','Final slides for tomorrow attached. Twelve slides plus an appendix. Cover slide and three section breaks; rest is content. Let me know if anything jumps out.','Re: Slides for tomorrow','Slides are tight. The cover messaging on slide 1 is a bit soft; consider leading with the headline number instead. Otherwise good to go.'),
  ('deliverable_handoff','Brief for the dev team','Engineering brief is ready. One page, requirements bulleted, acceptance criteria explicit. Edge cases listed at the end. Should be enough to scope.','Re: Brief for the dev team','Good brief. Clean structure. They will likely come back with one or two clarifications on the edge cases; will route them to you.'),
  ('deliverable_handoff','Survey design ready','Survey design ready in the shared doc. Fifteen questions, five required, ten optional. Logic for question 8 branches based on question 7.','Re: Survey design ready','Saw the doc. Question 8 logic looks right. Question 12 might be loaded; consider neutralising the wording before launch.'),
  ('deliverable_handoff','Final policy doc','Final policy doc is attached. Eight pages, signatures pending. Once you sign it off I will circulate to the wider team and post on the intranet.','Re: Final policy doc','Signed and returned. Good iteration cycle on this one. Worth a short email to the team highlighting the key changes.'),
  ('deliverable_handoff','Pricing model','Pricing model attached. Three tiers, gross margin assumptions on tab 2, sensitivity analysis on tab 3. Worth a 20-minute call to walk you through if useful.','Re: Pricing model','Looked at tab 2 and 3. Sensitivity analysis covers the right variables. 20-minute call will be useful before the customer conversation; book it in.'),
  ('deliverable_handoff','Onboarding playbook v2','v2 of the playbook is in the repository. Two new sections, one removed for being out of date. Diff is clean if you want to skim.','Re: Onboarding playbook v2','Skimmed the diff. The new section on integration partners is the most valuable addition; flag it in the changelog.'),
  ('deliverable_handoff','Annual report data tables','Data tables for the annual report attached. Five tabs, formatted, sources cited. Ready for the design team.','Re: Annual report data tables','Clean tables. Forwarding to design today. They will probably ask for a fresh export of tab 4 if the close is delayed.'),

  -- status_report (8)
  ('status_report','Weekly status update','Quick weekly status. On track on the two priority workstreams. The third is amber due to a vendor delay; mitigations are in motion. No new risks this week.','Re: Weekly status update','Thanks. The amber one is the one to watch; please keep me in the loop if the vendor slips again. Otherwise rhythm looks healthy.'),
  ('status_report','Project Phoenix update','Project Phoenix is on track for the late-month milestone. Three risks remain on the register; two trending down, one flat. Engineering ramping next week.','Re: Project Phoenix update','Glad two are trending down. The flat one needs a clear owner before next week so it does not drift.'),
  ('status_report','Customer cohort metrics','April cohort metrics in. Activation up 7 percent over March, week-4 retention flat. Two segments under-indexed; investigation queued.','Re: Customer cohort metrics','Activation lift is encouraging. Flat retention is the one to chase; tell me what the investigation surfaces.'),
  ('status_report','Hiring funnel snapshot','Hiring funnel update. Eight live roles, three at offer stage, two in second round, three at top of funnel. Diversity of the pipeline has improved over Q1.','Re: Hiring funnel snapshot','Solid progress. Pipeline diversity is the metric I care about most; nice to see it moving in the right direction.'),
  ('status_report','Compliance audit prep','Pre-audit walkthrough scheduled for next week. Documentation collected, evidence library refreshed, control owners briefed. Should be a clean cycle.','Re: Compliance audit prep','Good prep. The cleaner the cycle, the more the auditors trust subsequent ones. Keep the evidence library tidy after the audit closes.'),
  ('status_report','Incident retrospective','Last week''s incident retro is complete. Root cause identified, three preventive actions agreed, owners assigned. Detail in the doc.','Re: Incident retrospective','Thorough retro. The preventive action on the alerting threshold is the most important one; check it is in place before next week.'),
  ('status_report','Vendor consolidation review','Vendor consolidation review done. Recommending we sunset two minor tools and consolidate into the existing platform. Estimated saving below.','Re: Vendor consolidation review','Approved in principle. Confirm the data migration plan for each tool before pulling the plug.'),
  ('status_report','Monthly KPI snapshot','Monthly KPI snapshot attached. Six out of seven on target. The miss is on time-to-resolution for tier 2 tickets; staffing change last month is the driver.','Re: Monthly KPI snapshot','Six out of seven is acceptable given the staffing context. Make sure the resolution-time recovery curve is tracked through to next month.'),

  -- casual_acknowledgement (6)
  ('casual_acknowledgement','Thanks for the intro','Quick thanks for the warm intro on Friday. The conversation went well and a follow-up is scheduled for next week. Appreciated.','Re: Thanks for the intro','Glad it went well. Let me know how the follow-up lands; happy to share more context if useful.'),
  ('casual_acknowledgement','Appreciate the heads-up','Cheers for the early heads-up on the customer ticket. Sorted in time and the customer landed soft.','Re: Appreciate the heads-up','No problem. Better to catch these early. Keep doing what you''re doing on response times.'),
  ('casual_acknowledgement','Loved the article','Saw your piece on the topic this morning. Best summary I have read on it. Forwarding to the team.','Re: Loved the article','Thanks for sharing. The team feedback usually surfaces angles I missed; let me know if anything jumps out.'),
  ('casual_acknowledgement','Good catch','Spotted the issue in the deck on slide 6. Good catch before the meeting. Fixed and re-uploaded.','Re: Good catch','Glad it was easy to fix. Better caught now than in front of the audience.'),
  ('casual_acknowledgement','Welcome aboard','Welcome to the team. The first two weeks are mostly meeting people and reading docs; you do not need to ship anything yet. Reach out if anything is unclear.','Re: Welcome aboard','Thanks for the warm welcome. Will spend the first few days reading and meeting people, then start shadowing one of the projects.'),
  ('casual_acknowledgement','Out of office set','Heading out for a week starting Friday. Auto-responder will be on; for anything urgent please reach the team alias.','Re: Out of office set','Noted. Have a good break.')

ON CONFLICT DO NOTHING;
