-- Phase 6.9 · Add 12 high-impact frameworks + ~45 new rules.
-- Adds: DPA 2018, ePrivacy, EU AI Act, CCPA, HIPAA, ADA, SEC Reg FD, RERA, Trakheesi, FCA MAR, Google E-E-A-T, FINRA 2210.

BEGIN;

INSERT INTO framework_versions (framework_short, framework_name, jurisdiction, version, rules_count, status, notes) VALUES
  ('UK_DPA_2018',       'Data Protection Act 2018',                    'UK', '2018.1', 0, 'live', 'UK GDPR companion statute'),
  ('EU_EPRIVACY',       'ePrivacy Regulation',                          'EU', '2026.1', 0, 'live', 'electronic communications + cookies'),
  ('EU_AI_ACT',         'EU AI Act (Regulation (EU) 2024/1689)',        'EU', '2024.1', 0, 'live', 'AI system risk-tier rules'),
  ('US_CCPA',           'CCPA / CPRA',                                  'US', '2023.1', 0, 'live', 'California consumer privacy'),
  ('US_HIPAA',          'HIPAA Privacy Rule · 45 CFR 164',              'US', '2024.1', 0, 'live', 'protected health information'),
  ('US_ADA',            'ADA Title III Digital Accessibility',          'US', '2024.1', 0, 'live', 'DOJ April 2024 rule'),
  ('US_SEC_REG_FD',     'SEC Regulation FD',                            'US', '2024.1', 0, 'live', 'fair disclosure'),
  ('UAE_RERA',          'RERA Law No. 7 of 2013 · Trakheesi',           'AE', '2024.1', 0, 'live', 'Dubai real estate marketing'),
  ('UK_FCA_MAR',        'FCA MAR',                                       'UK', '2024.1', 0, 'live', 'market abuse'),
  ('GOOGLE_EEAT',       'Google E-E-A-T Quality Rater Guidelines',      'GLOBAL', '2024.1', 0, 'live', 'experience expertise authoritativeness trust'),
  ('US_FINRA_2210',     'FINRA Rule 2210',                              'US', '2024.1', 0, 'live', 'broker-dealer communications'),
  ('UK_FOOD_INFO_2014', 'Food Information Regulations 2014',            'UK', '2024.1', 0, 'live', 'allergens + Natashas Law')
ON CONFLICT (framework_short) DO NOTHING;

-- ============================================================================
-- DPA 2018
-- ============================================================================
INSERT INTO compliance_rules (framework_short, rule_id, description, regex_pattern, url_check, severity, citation_url, active) VALUES
  ('UK_DPA_2018', 'S3', 'Section 3 personal data definition disclosure', '(personal data|data subject)', '/privacy', 'P1', 'https://www.legislation.gov.uk/ukpga/2018/12/section/3', TRUE),
  ('UK_DPA_2018', 'S22', 'Section 22 manual unstructured data exemption noted where applicable', '(manual unstructured|public authority)', '/privacy', 'P2', 'https://www.legislation.gov.uk/ukpga/2018/12/section/22', TRUE)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- EU AI Act
-- ============================================================================
INSERT INTO compliance_rules (framework_short, rule_id, description, regex_pattern, url_check, severity, citation_url, active) VALUES
  ('EU_AI_ACT', 'ART4', 'AI literacy disclosure for AI-enabled customer-facing tools', '(ai (system|tool)|chatbot|generative ai|automated decision)', '/', 'P1', 'https://artificialintelligenceact.eu/article/4/', TRUE),
  ('EU_AI_ACT', 'ART5', 'Prohibited AI practices avoided (no social scoring, no manipulation)', '(social scoring|emotion recognition|biometric categorisation)', '/', 'P0', 'https://artificialintelligenceact.eu/article/5/', TRUE),
  ('EU_AI_ACT', 'ART6', 'High-risk AI system disclosure (CV screening, credit scoring, medical)', '(cv screening|credit scoring|medical ai|biometric identification)', '/', 'P0', 'https://artificialintelligenceact.eu/article/6/', TRUE),
  ('EU_AI_ACT', 'ART50', 'Transparency obligation: notice that user is interacting with AI', '(generated by ai|powered by ai|ai-generated|disclosure: ai)', '/', 'P0', 'https://artificialintelligenceact.eu/article/50/', TRUE),
  ('EU_AI_ACT', 'ART53', 'GPAI model transparency disclosure', '(general[- ]?purpose ai|gpai|foundation model)', '/about|/legal|/ai', 'P1', 'https://artificialintelligenceact.eu/article/53/', TRUE)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- ePrivacy
-- ============================================================================
INSERT INTO compliance_rules (framework_short, rule_id, description, regex_pattern, url_check, severity, citation_url, active) VALUES
  ('EU_EPRIVACY', 'A6', 'Confidentiality of electronic communications notice', '(electronic communications|cookies|tracking technologies)', '/privacy|/cookies', 'P1', 'https://eur-lex.europa.eu/', TRUE),
  ('EU_EPRIVACY', 'A8', 'Cookies + similar technologies prior-consent banner', '(cookie consent|cookie banner|prior consent)', '/', 'P0', 'https://eur-lex.europa.eu/', TRUE),
  ('EU_EPRIVACY', 'A16', 'Unsolicited commercial communications opt-in for natural persons', '(opt[- ]?in|unsubscribe|preferences)', '/privacy|/contact', 'P1', 'https://eur-lex.europa.eu/', TRUE)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- CCPA / CPRA
-- ============================================================================
INSERT INTO compliance_rules (framework_short, rule_id, description, regex_pattern, url_check, severity, citation_url, active) VALUES
  ('US_CCPA', '1798.135', 'Do Not Sell or Share My Personal Information link', '(do not sell.{0,20}(my )?personal|opt[- ]?out of sale|do not share)', '/', 'P0', 'https://oag.ca.gov/privacy/ccpa', TRUE),
  ('US_CCPA', '1798.100', 'Right-to-know disclosure on data collected', '(right to know|categories of personal information|sources of personal information)', '/privacy', 'P0', 'https://oag.ca.gov/privacy/ccpa', TRUE),
  ('US_CCPA', '1798.105', 'Right to delete disclosure', '(right to delete|delete (my )?(personal )?(data|information))', '/privacy', 'P0', 'https://oag.ca.gov/privacy/ccpa', TRUE),
  ('US_CCPA', '1798.120', 'Right to opt out of sale or sharing', '(opt out of (the )?sale|opt out of (the )?sharing)', '/privacy', 'P0', 'https://oag.ca.gov/privacy/ccpa', TRUE)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- HIPAA
-- ============================================================================
INSERT INTO compliance_rules (framework_short, rule_id, description, regex_pattern, url_check, severity, citation_url, active) VALUES
  ('US_HIPAA', '164.508', 'Authorisation for use or disclosure of PHI for marketing', '(authorisation|authorization|written consent|hipaa authorization)', '/privacy|/legal', 'P0', 'https://www.ecfr.gov/current/title-45/section-164.508', TRUE),
  ('US_HIPAA', '164.520', 'Notice of Privacy Practices', '(notice of privacy practices|npp|hipaa notice)', '/privacy', 'P0', 'https://www.ecfr.gov/current/title-45/section-164.520', TRUE),
  ('US_HIPAA', '164.530', 'Business Associate Agreements disclosed', '(business associate|baa|business associate agreement)', '/privacy|/legal', 'P1', 'https://www.ecfr.gov/current/title-45/section-164.530', TRUE)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- ADA Digital Accessibility (DOJ April 2024 rule for state and local govts; widely applied to private sector)
-- ============================================================================
INSERT INTO compliance_rules (framework_short, rule_id, description, regex_pattern, url_check, severity, citation_url, active) VALUES
  ('US_ADA', 'WCAG_AA', 'WCAG 2.1 AA accessibility statement', '(accessibility statement|wcag|web content accessibility guidelines|ada compliance)', '/accessibility|/legal|/footer', 'P1', 'https://www.ada.gov/notices/2024/04/24/web-accessibility-final-rule/', TRUE)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- SEC Reg FD
-- ============================================================================
INSERT INTO compliance_rules (framework_short, rule_id, description, regex_pattern, url_check, severity, citation_url, active) VALUES
  ('US_SEC_REG_FD', '243.100', 'Fair disclosure on material non-public information', '(material non[- ]?public information|reg fd|regulation fd|fair disclosure)', '/investors|/legal', 'P0', 'https://www.sec.gov/rules/final/33-7881.htm', TRUE),
  ('US_SEC_REG_FD', 'IR_PAGE', 'Investor relations page exists with current disclosures', '(investor relations|press releases|sec filings|quarterly earnings)', '/investors', 'P0', 'https://www.sec.gov/rules/final/33-7881.htm', TRUE)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- RERA / Trakheesi (UAE)
-- ============================================================================
INSERT INTO compliance_rules (framework_short, rule_id, description, regex_pattern, url_check, severity, citation_url, active) VALUES
  ('UAE_RERA', 'L7_2013', 'RERA Law No. 7 of 2013 broker registration disclosure', '(rera (no|number|registration)|registered broker|brn[\\s:]?\\d)', '/about|/legal', 'P0', 'https://dubailand.gov.ae/', TRUE),
  ('UAE_RERA', 'TRAKHEESI', 'Trakheesi permit number visible on every advertised listing', '(trakheesi|permit (no|number)|ad permit)', '/listings|/properties|/', 'P0', 'https://dubailand.gov.ae/', TRUE)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- FCA MAR (Market Abuse Regulation)
-- ============================================================================
INSERT INTO compliance_rules (framework_short, rule_id, description, regex_pattern, url_check, severity, citation_url, active) VALUES
  ('UK_FCA_MAR', '1.3', 'Inside information disclosure timeliness', '(inside information|primary insiders|insider list)', '/investors|/legal', 'P0', 'https://www.handbook.fca.org.uk/handbook/MAR.pdf', TRUE)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- Google E-E-A-T (not regulatory but ranking-critical)
-- ============================================================================
INSERT INTO compliance_rules (framework_short, rule_id, description, regex_pattern, url_check, severity, citation_url, active) VALUES
  ('GOOGLE_EEAT', 'AUTHOR', 'Author byline on substantive content (Experience + Expertise)', '(written by|author:|by [A-Z][a-z]+ [A-Z][a-z]+|bio|about the author)', '/blog|/insights|/articles|/', 'P1', 'https://developers.google.com/search/docs/fundamentals/creating-helpful-content', TRUE),
  ('GOOGLE_EEAT', 'CREDENTIALS', 'Author credentials visible (Authoritativeness)', '(llb|llm|aca|fcca|mrics|frsa|chartered|admitted|barrister|solicitor|partner)', '/about|/team|/people|/blog', 'P1', 'https://developers.google.com/search/docs/fundamentals/creating-helpful-content', TRUE),
  ('GOOGLE_EEAT', 'CITATIONS', 'Citations to authoritative sources (Trust)', '(<a [^>]*href=[\"''](https?:)?//[^\"'']+(\\.gov(\\.uk)?|\\.ac\\.uk|wikipedia\\.org|nhs\\.uk))', '/blog|/insights|/', 'P2', 'https://developers.google.com/search/docs/fundamentals/creating-helpful-content', TRUE)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- FINRA 2210 (broker-dealer communications)
-- ============================================================================
INSERT INTO compliance_rules (framework_short, rule_id, description, regex_pattern, url_check, severity, citation_url, active) VALUES
  ('US_FINRA_2210', 'D2', 'Past-performance disclosure on broker-dealer comms', '(past performance|results may vary|not indicative)', '/investors|/legal|/disclosures', 'P0', 'https://www.finra.org/rules-guidance/rulebooks/finra-rules/2210', TRUE)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- Food Information Regulations 2014 (Natasha's Law)
-- ============================================================================
INSERT INTO compliance_rules (framework_short, rule_id, description, regex_pattern, url_check, severity, citation_url, active) VALUES
  ('UK_FOOD_INFO_2014', 'NATASHA', '14 allergens disclosed on every food product page (PPDS)', '(allergen|may contain|gluten|peanuts|tree nuts|sesame|sulphites|natasha)', '/menu|/products|/food', 'P0', 'https://www.legislation.gov.uk/uksi/2014/1855/contents/made', TRUE),
  ('UK_FOOD_INFO_2014', 'CALORIES', 'Calorie information on out-of-home menus (Calorie Labelling Regulations 2021)', '(calorie|kcal|per serving)', '/menu|/food', 'P0', 'https://www.legislation.gov.uk/uksi/2021/909/made', TRUE)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- Sector framework routing extension — wire new frameworks into jurisdiction-router scope
-- (Code change handled separately in src/lib/compliance/jurisdiction-router.js)
-- ============================================================================

COMMIT;

-- Summary
SELECT
  (SELECT COUNT(*) FROM framework_versions) AS frameworks,
  (SELECT COUNT(*) FROM compliance_rules WHERE active=TRUE) AS active_rules;
