-- Seed template_variants for the 5 active Tamazia sectors × 3 touches × 3 variants (A/B/C).
-- Allocation: A=80, B=10, C=10 (winner-takes-most with two challengers).
-- Phase 3 retains immutable history: variants don't get deleted, only archived.

WITH seeds(sector, touch, variant_letter, allocation_pct, subject_template, body_template, variant_kind) AS (VALUES
  -- HOSPITALITY · touch 0
  ('hospitality',0,'A',80,
    '{firm} · PECR Reg 6 signal worth a look',
    '{first_name}, a quick PECR observation on {firm}. The analytics tag fires before the cookie consent banner accepts on the booking flow. ICO sweep treats this as P0 and the rankings impact is measurable. A comparable hotel group closed the gap and recovered organic visibility inside 30 days. Open to me sending a complimentary Regulatory Signal Scan of the site? Findings yours to keep. cal.com/tamazia/strategy-call.',
    'regulatory'),
  ('hospitality',0,'B',10,
    '{firm} · cookie consent + GA4 visibility',
    '{first_name}, sharing one observation on {firm}. GA4 loads pre-consent on the public booking pages. ICO and Google''s 2024 stance have both shifted; ranking effect compounds quarter by quarter. A comparable property recovered ~18% organic in six weeks after the fix. Happy to share the same scan for {firm} on request, no obligation. cal.com/tamazia/strategy-call.',
    'site_change'),
  ('hospitality',0,'C',10,
    '{firm} · 7-day audit window on cookies',
    '{first_name}, light note on {firm}. Cookie banner currently allows analytics by implicit consent, which is materially out of step with the 2024 ICO position. Two London hotel groups corrected this in May with measurable booking-organic uplift. With your permission I can pull together a 21-check scan tailored to {firm} this week. cal.com/tamazia/strategy-call.',
    'switching_agency'),
  -- HOSPITALITY · touch 1 (follow-up)
  ('hospitality',1,'A',80,
    'Re: {firm} · PECR Reg 6 signal',
    '{first_name}, the {firm} observation is still standing. The fix is roughly two engineering days and unlocks organic gains worth far more than the cost of action. Diagnostic still available if useful. cal.com/tamazia/strategy-call.',
    'follow_up'),
  ('hospitality',1,'B',10,
    'Re: {firm} · quick follow on the audit window',
    '{first_name}, briefly following — happy to share the scan brief for {firm} when convenient. cal.com/tamazia/strategy-call.',
    'follow_up'),
  ('hospitality',1,'C',10,
    'Re: {firm} · two minutes if useful',
    '{first_name}, sending one short reminder. The scan brief is ready for {firm} when you have two minutes. cal.com/tamazia/strategy-call.',
    'follow_up'),
  -- HEALTHCARE · touch 0
  ('healthcare',0,'A',80,
    '{firm} · MHRA + CAP Section 12 signal',
    '{first_name}, a healthcare-marketing observation on {firm}. Two service pages cite outcomes without ASA-compliant substantiation, and the cookie banner sets analytics pre-consent. MHRA + CAP 12 enforcement has accelerated in 2024. A comparable private clinic group fixed both and saw organic uplift in five weeks. Open to a complimentary Regulatory Signal Scan? cal.com/tamazia/strategy-call.',
    'regulatory'),
  ('healthcare',0,'B',10,
    '{firm} · 21-check scan tailored to your sector',
    '{first_name}, sharing one note on {firm}. ASA CAP 12 substantiation + cookie behaviour both look correctable within a sprint. Recent clinic case study showed 22% organic recovery. Happy to send the scan for {firm} when convenient. cal.com/tamazia/strategy-call.',
    'site_change'),
  ('healthcare',0,'C',10,
    '{firm} · CQC + ICO + ASA cross-check',
    '{first_name}, observation on {firm}. The CQC rating display + ASA testimonial wording + cookie analytics gating all currently miss thresholds the 2024 enforcement pattern is targeting. Two private GP groups corrected and recovered organic in under a quarter. With your permission I can scan {firm}. cal.com/tamazia/strategy-call.',
    'switching_agency'),
  ('healthcare',1,'A',80,
    'Re: {firm} · MHRA + CAP 12 follow',
    '{first_name}, brief follow. Scan brief is ready when you have two minutes. cal.com/tamazia/strategy-call.',
    'follow_up'),
  ('healthcare',1,'B',10,
    'Re: {firm} · quick check-in',
    '{first_name}, light follow on {firm} — happy to share the scan when convenient. cal.com/tamazia/strategy-call.',
    'follow_up'),
  ('healthcare',1,'C',10,
    'Re: {firm} · the diagnostic is ready',
    '{first_name}, diagnostic ready when you can spare two minutes. cal.com/tamazia/strategy-call.',
    'follow_up'),
  -- REAL-ESTATE · touch 0
  ('real-estate',0,'A',80,
    '{firm} · CMA price display + RICS Lettings Code',
    '{first_name}, observation on {firm}. The current listing pages set permitted-payment disclosure under the Tenant Fees Act in a way the 2024 CMA cases are flagging. Cookie consent on the search funnel also fires GA4 pre-consent. A comparable agency closed both and improved organic listings impressions ~24%. Open to a complimentary Regulatory Signal Scan? cal.com/tamazia/strategy-call.',
    'regulatory'),
  ('real-estate',0,'B',10,
    '{firm} · 21-check scan for property pages',
    '{first_name}, light note on {firm}. CMA price-display + RICS Lettings Code + cookie consent — all fixable inside a sprint with measurable ranking impact. Happy to share the scan for {firm}. cal.com/tamazia/strategy-call.',
    'site_change'),
  ('real-estate',0,'C',10,
    '{firm} · property listings audit window',
    '{first_name}, observation on {firm}. The valuation funnel currently exposes price-bracket pages that the 2024 enforcement against unfair price-display patterns is targeting. Recent agency corrected and recovered organic in 6 weeks. With permission I can scan {firm} this week. cal.com/tamazia/strategy-call.',
    'switching_agency'),
  ('real-estate',1,'A',80,
    'Re: {firm} · CMA + RICS follow',
    '{first_name}, brief follow on the {firm} observation. Scan brief is ready when convenient. cal.com/tamazia/strategy-call.',
    'follow_up'),
  ('real-estate',1,'B',10,
    'Re: {firm} · two minutes on listings',
    '{first_name}, sending one short reminder; happy to share the scan for {firm}. cal.com/tamazia/strategy-call.',
    'follow_up'),
  ('real-estate',1,'C',10,
    'Re: {firm} · diagnostic ready',
    '{first_name}, diagnostic ready when convenient. cal.com/tamazia/strategy-call.',
    'follow_up'),
  -- LAW-FIRMS · touch 0
  ('law-firms',0,'A',80,
    '{firm} · SRA Transparency Rules observation',
    '{first_name}, observation on {firm}. The conveyancing and family-law service pages currently miss SRA Transparency price-display thresholds that the SRA 2024 enforcement is targeting actively. A comparable firm closed the gap and recovered organic visibility on three commercial keywords. Open to a complimentary Regulatory Signal Scan? cal.com/tamazia/strategy-call.',
    'regulatory'),
  ('law-firms',0,'B',10,
    '{firm} · 21-check legal-services scan',
    '{first_name}, sharing one observation on {firm}. SRA Transparency Rules + ICO cookie + CMA price-display — three frameworks layered on the same surface and all checkable in one scan. Happy to share for {firm}. cal.com/tamazia/strategy-call.',
    'site_change'),
  ('law-firms',0,'C',10,
    '{firm} · complaints page + SRA badge audit',
    '{first_name}, observation on {firm}. The published complaints procedure + SRA badge placement are the two most common audit findings in the 2024 SRA review pattern. With your permission I can scan {firm} this week. cal.com/tamazia/strategy-call.',
    'switching_agency'),
  ('law-firms',1,'A',80,
    'Re: {firm} · SRA follow',
    '{first_name}, brief follow on {firm}. Scan brief is ready when convenient. cal.com/tamazia/strategy-call.',
    'follow_up'),
  ('law-firms',1,'B',10,
    'Re: {firm} · two minutes on transparency',
    '{first_name}, light follow on {firm} — happy to share the scan. cal.com/tamazia/strategy-call.',
    'follow_up'),
  ('law-firms',1,'C',10,
    'Re: {firm} · diagnostic ready',
    '{first_name}, diagnostic ready when convenient. cal.com/tamazia/strategy-call.',
    'follow_up'),
  -- FINANCE · touch 0
  ('finance',0,'A',80,
    '{firm} · FCA CONC 2.5 promotion observation',
    '{first_name}, observation on {firm}. The credit-product landing pages currently set risk warnings with materially lower visual weight than the headline rate, which FCA CONC 2.5 + the 2024 Section 21 regime have been actively pressing on. A comparable firm closed the gap and recovered organic visibility on three core keywords. Open to a complimentary Regulatory Signal Scan? cal.com/tamazia/strategy-call.',
    'regulatory'),
  ('finance',0,'B',10,
    '{firm} · 21-check finance-services scan',
    '{first_name}, light note on {firm}. CONC 2.5 + ICO cookie + ASA financial-promotions code — three frameworks on one funnel, all checkable in one scan. Happy to share for {firm}. cal.com/tamazia/strategy-call.',
    'site_change'),
  ('finance',0,'C',10,
    '{firm} · APR disclosure pattern',
    '{first_name}, observation on {firm}. The APR disclosure pattern on the BNPL pages aligns with the 2024 Klarna-style enforcement signals. With your permission I can scan {firm} this week. cal.com/tamazia/strategy-call.',
    'switching_agency'),
  ('finance',1,'A',80,
    'Re: {firm} · CONC 2.5 follow',
    '{first_name}, brief follow on {firm}. Scan brief is ready when convenient. cal.com/tamazia/strategy-call.',
    'follow_up'),
  ('finance',1,'B',10,
    'Re: {firm} · two minutes on promotions',
    '{first_name}, light follow on {firm} — happy to share the scan. cal.com/tamazia/strategy-call.',
    'follow_up'),
  ('finance',1,'C',10,
    'Re: {firm} · diagnostic ready',
    '{first_name}, diagnostic ready when convenient. cal.com/tamazia/strategy-call.',
    'follow_up')
)
INSERT INTO template_variants (workspace_id, sector, touch, variant_letter, allocation_pct, subject_template, body_template, variant_kind)
SELECT 1, sector, touch, variant_letter, allocation_pct, subject_template, body_template, variant_kind FROM seeds
ON CONFLICT (workspace_id, sector, touch, variant_letter) DO NOTHING;

-- Mirror seeded subjects into subject_variants so subject A/B can rotate independently of body.
INSERT INTO subject_variants (workspace_id, sector, touch, variant_letter, allocation_pct, subject_template)
SELECT workspace_id, sector, touch, variant_letter, allocation_pct, subject_template FROM template_variants
ON CONFLICT (workspace_id, sector, touch, variant_letter) DO NOTHING;
