'use strict';
// registry/framework-intel.js
// CANONICAL sector-framework legal-intelligence overlay (V2 §4: Framework × Regulator × Obligation × Penalty, sector slice).
// ONE structured record per framework. The FULL statutory citation stays in the Neon catalogue
// (compliance_rules.statutory_citation) — this overlay is NOT a second citation store; it holds the
// structured intelligence the catalogue does not model at the framework level and that V1 named missing:
//   binding (V1 B7 — no binding-status dimension), the activating trigger predicate, the TYPED evidence a
//   compliant site must show (V1 B6/C10 — "a duty with an evidence type, not a regex over text"), the
//   deterministic detect signal (before LLM), the regulator, the instrument short-name, enforcement, the
//   jurisdiction, and the web-verified current version.
// Brings the SECTOR layer to the depth registry/obligations.js gave the UNIVERSAL layer. No duplication:
// every code here must exist in the catalogue (framework-intel.test.js asserts it); citations are referenced, not copied.
// Sources: Neon catalogue citations (pulled 2026-06-30) + Architecture Review V1 (immutable) + Research Report 2
//   + web verification 2026-06-30 (SRA current rules 11-Apr-2025; FCA Consumer Duty closed-products 31-Jul-2024; DMCC consumer regime 6-Apr-2025).

const BINDING = Object.freeze({
  STATUTE:'statute',                 // legislation, directly binding
  STAT_CODE:'statutory_code',        // code/rules made under statutory power, binding on the regulated population
  REG_CODE:'regulator_code',         // regulator/co-regulatory code, binding in practice (ASA/CAP backed by CMA/Ofcom)
  PROF_CODE:'professional_code',     // professional body rules, binding on members
  REDRESS:'statutory_redress',       // redress-scheme membership mandated by statute
  VOLUNTARY:'voluntary_code'         // voluntary trade-body code — NOT binding law (must be labelled as such)
});

const INTEL = {
  UK_SRA_TRANSPARENCY: { regulator:'Solicitors Regulation Authority (SRA)', instrument:'SRA Transparency Rules (current version in force 11 Apr 2025), under Legal Services Act 2007 ss 12-15', binding:BINDING.STAT_CODE, trigger:'offers_reserved_legal_activity', evidence:['published cost/price information for the listed services','complaints procedure incl. how & when to complain to the Legal Ombudsman and SRA','SRA-prescribed clickable digital badge','SRA number / regulated-status statement'], detect:'price + complaints + SRA badge URL present on a regulated-services page', enforcement:'Active: 439 official warnings + 36 fixed penalties since May 2023; 500+ non-compliant sites changed (SRA 2024-25).', jurisdiction:'UK', updated:'2025-04-11' },
  UK_SRA_COC: { regulator:'Solicitors Regulation Authority (SRA)', instrument:'SRA Code of Conduct for Solicitors / Firms (Standards & Regulations 2019)', binding:BINDING.STAT_CODE, trigger:'offers_reserved_legal_activity', evidence:['accurate regulated-status / not-misleading publicity','clear identification of the regulated body'], detect:'regulated-status statement consistent with SRA register', enforcement:'SRA disciplinary action; referral to SDT for serious breaches.', jurisdiction:'UK', updated:'2019-11-25' },
  UK_BSB: { regulator:'Bar Standards Board (BSB)', instrument:'BSB Handbook (Code of Conduct)', binding:BINDING.STAT_CODE, trigger:'is_barrister_or_chambers', evidence:['accurate, non-misleading public statements about services','complaints / regulated-status information'], detect:'chambers/barrister identity present AND SRA-firm rules absent (SUB_EXCLUSIVE)', enforcement:'BSB enforcement; disciplinary tribunal.', jurisdiction:'UK', updated:'2024-01-01' },

  UK_CQC: { regulator:'Care Quality Commission (CQC)', instrument:'Health and Social Care Act 2008 + (Regulated Activities) Regulations 2014 (SI 2014/2936)', binding:BINDING.STATUTE, trigger:'is_cqc_registered_provider', evidence:['CQC registration / provider ID where a regulated activity is carried on','accurate display of the current CQC rating'], detect:'regulated-activity language present AND CQC registration reference present', enforcement:'CQC: registration conditions, civil penalties, prosecution for unregistered regulated activity.', jurisdiction:'UK', updated:'2024-11-01' },
  UK_GMC: { regulator:'General Medical Council (GMC)', instrument:'GMC Good Medical Practice 2024', binding:BINDING.PROF_CODE, trigger:'doctor_led_service', evidence:['doctor identification with GMC reference','no misleading clinical claims'], detect:'doctor-led service claims present with verifiable GMC registration', enforcement:'GMC fitness-to-practise; MPTS sanctions.', jurisdiction:'UK', updated:'2024-01-30' },
  UK_HFEA: { regulator:'Human Fertilisation & Embryology Authority (HFEA)', instrument:'HFE Act 1990 (as amended) s.11/s.25/Sch.2 + HFEA Code of Practice (9th ed.) guidance note 30', binding:BINDING.STATUTE, trigger:'is_fertility_clinic', evidence:['HFEA licence reference','success rates presented accurately and not misleadingly','treatment add-ons presented with the HFEA evidence rating'], detect:'fertility/IVF sub-sector AND (success-rate or add-on claims) present', enforcement:'HFEA licensing conditions; ASA/CMA action on misleading success-rate or add-on claims.', jurisdiction:'UK', updated:'2024-01-01' },
  UK_GDC: { regulator:'General Dental Council (GDC)', instrument:'Dentists Act 1984 s.39 + GDC Standards for the Dental Team', binding:BINDING.STAT_CODE, trigger:'is_dental_practice', evidence:['accurate use of protected specialist titles (only if on the GDC specialist list)','clear pricing for treatments','no misleading cosmetic claims'], detect:'specialist-title claim present AND verifiable GDC specialist registration; price present', enforcement:'GDC fitness-to-practise; criminal offence to use a protected title falsely.', jurisdiction:'UK', updated:'2023-09-01' },
  UK_GPHC: { regulator:'General Pharmaceutical Council (GPhC)', instrument:'GPhC Standards for registered pharmacies + Human Medicines Regulations 2012', binding:BINDING.STAT_CODE, trigger:'mentions_medicines', evidence:['registered-pharmacy identification + GPhC number','online-pharmacy voluntary registration logo where applicable'], detect:'dispensing/online-pharmacy language present AND GPhC registration reference present', enforcement:'GPhC inspection, conditions, removal from register.', jurisdiction:'UK', updated:'2024-01-01' },
  UK_MHRA: { regulator:'Medicines & Healthcare products Regulatory Agency (MHRA)', instrument:'Human Medicines Regulations 2012 (SI 2012/1916) reg.280 (POM advertising ban) + regs 257/259', binding:BINDING.STATUTE, trigger:'mentions_pom_or_medicines', evidence:['no advertising of prescription-only medicines (e.g. Botox/botulinum toxin) to the public','medicine information not misleading; required particulars present'], detect:'POM brand/term (botox, botulinum, named POM) present in marketing context', enforcement:'MHRA criminal enforcement; ASA rulings. P0 severity.', jurisdiction:'UK', updated:'2012-08-14' },
  UK_ASA_CAP: { regulator:'Advertising Standards Authority (ASA) / CAP', instrument:'UK CAP Code (12th ed.) — r.3.1 misleading, r.3.7 substantiation, r.3.18 price, r.12.x health/cosmetic', binding:BINDING.REG_CODE, trigger:'makes_marketing_claims', evidence:['substantiation for objective/health claims','price claims include non-optional taxes (VAT)','cosmetic-intervention ads not targeted at under-18s'], detect:'health/cosmetic/price claim present without substantiation or VAT-inclusive pricing', enforcement:'ASA rulings, ad removal, CMA/Trading Standards backstop.', jurisdiction:'UK', updated:'2024-01-01' },

  UK_FCA_CONSUMER_DUTY: { regulator:'Financial Conduct Authority (FCA)', instrument:'FCA Handbook PRIN 2A; Principle 12; FG22/5', binding:BINDING.STATUTE, trigger:'promotes_financial_products', evidence:['evidence of good consumer outcomes (products & services, price & value, understanding, support)','clear, not-misleading consumer-facing communications'], detect:'retail financial product/service promoted to consumers', enforcement:'FCA supervisory/enforcement action; in force 31 Jul 2023 (open) and 31 Jul 2024 (closed products).', jurisdiction:'UK', updated:'2024-07-31' },
  UK_FCA_CONDUCT: { regulator:'Financial Conduct Authority (FCA)', instrument:'FCA Conduct of Business Sourcebook (COBS) + Consumer Duty', binding:BINDING.STATUTE, trigger:'promotes_financial_products', evidence:['COBS-compliant disclosures','fair, clear, not-misleading communications'], detect:'regulated financial activity promoted; FCA authorisation reference present', enforcement:'FCA enforcement; redress.', jurisdiction:'UK', updated:'2023-07-31' },
  UK_FSMA_S21: { regulator:'Financial Conduct Authority (FCA)', instrument:'FSMA 2000 s.21 (financial promotion restriction) + FCA COBS 4 + Financial Promotion Order; cryptoasset promotions regime', binding:BINDING.STATUTE, trigger:'communicates_financial_promotion', evidence:['promotion approved/communicated by an authorised person','prescribed risk warning (incl. cryptoasset risk warning + cooling-off)'], detect:'investment/crypto promotion present without authorised-person approval or risk warning', enforcement:'s.21 is a criminal offence (s.25); FCA enforcement. P0 severity.', jurisdiction:'UK', updated:'2023-10-08' },
  UK_ICOBS: { regulator:'Financial Conduct Authority (FCA)', instrument:'FCA Insurance: Conduct of Business Sourcebook (ICOBS)', binding:BINDING.STATUTE, trigger:'sells_insurance', evidence:['ICOBS pre-contract disclosures','fair value (IPID where applicable)'], detect:'insurance distribution activity present', enforcement:'FCA enforcement.', jurisdiction:'UK', updated:'2023-07-31' },
  UK_ABI: { regulator:'Association of British Insurers (ABI) — trade body', instrument:'ABI Codes of Practice (e.g. funeral plans, genetics) — VOLUNTARY', binding:BINDING.VOLUNTARY, trigger:'sells_insurance', evidence:['adherence to the relevant ABI code IF the firm is an ABI member and an insurer'], detect:'INSURER sub-sector only (SUB_EXCLUSIVE: never bank/wealth/IFA — V1 B7)', enforcement:'Voluntary; no statutory penalty. Render as a voluntary commitment, not binding law.', jurisdiction:'UK', updated:'2023-01-01' },

  UK_ESTATE_AGENTS_ACT: { regulator:'National Trading Standards / CMA', instrument:'Estate Agents Act 1979 (ss.18, 21, 3) + Consumers, Estate Agents and Redress Act 2007', binding:BINDING.STATUTE, trigger:'is_estate_or_letting_agent', evidence:['disclosure of fees and services','disclosure of personal interest','redress-scheme membership'], detect:'estate-agency activity present without fee/redress disclosure', enforcement:'Trading Standards; banning orders; redress.', jurisdiction:'UK', updated:'2007-01-01' },
  UK_TPO: { regulator:'The Property Ombudsman (TPO) — approved redress scheme', instrument:'TPO Codes of Practice (membership mandated by the 2007 Act for agents)', binding:BINDING.REDRESS, trigger:'is_estate_or_letting_agent', evidence:['display of redress-scheme (TPO) membership'], detect:'agency activity present AND redress-scheme membership statement present', enforcement:'Statutory requirement to belong to an approved redress scheme; Trading Standards enforce membership.', jurisdiction:'UK', updated:'2024-01-01' },
  UK_TENANT_FEES_2019: { regulator:'Local Trading Standards', instrument:'Tenant Fees Act 2019 ss.1-3 + Sch.1 (permitted payments)', binding:BINDING.STATUTE, trigger:'is_estate_or_letting_agent', evidence:['no prohibited tenant fees advertised','only permitted payments listed'], detect:'lettings sub-sector AND a prohibited-fee term present', enforcement:'Trading Standards: penalties up to GBP 5,000 (first) / 30,000 (repeat).', jurisdiction:'UK', updated:'2019-06-01' },
  UK_RICS: { regulator:'Royal Institution of Chartered Surveyors (RICS)', instrument:'RICS Rules of Conduct (2022)', binding:BINDING.PROF_CODE, trigger:'is_estate_or_letting_agent', evidence:['accurate RICS-regulated identification','professional standards in property marketing'], detect:'RICS-regulated claim present AND verifiable RICS membership', enforcement:'RICS regulatory/disciplinary action on members.', jurisdiction:'UK', updated:'2022-02-01' },

  UK_DMCC_2024: { regulator:'Competition & Markets Authority (CMA)', instrument:'Digital Markets, Competition and Consumers Act 2024 (consumer provisions in force 6 Apr 2025)', binding:BINDING.STATUTE, trigger:'sells_to_consumers', evidence:['total price incl. all mandatory charges shown at the first point pricing is displayed (no drip pricing)','no fake/incentivised reviews; reasonable steps to prevent and remove them'], detect:'consumer pricing with mandatory fees revealed late, OR review content without provenance controls', enforcement:'CMA DIRECT fines up to 10% global turnover or GBP 300k (fake-reviews grace ended ~Jul 2025).', jurisdiction:'UK', updated:'2025-04-06' },
  UK_FOOD_INFO_2014: { regulator:'Food Standards Agency / Local Authorities', instrument:'Food Information Regulations 2014 (retained EU FIC 1169/2011)', binding:BINDING.STATUTE, trigger:'sells_food_online', evidence:['allergen information for food sold/ordered online','accurate food descriptions'], detect:'online food ordering present without allergen information', enforcement:'Local authority enforcement; fines.', jurisdiction:'UK', updated:'2014-12-13' },

  BAHRAIN_PDPL: { regulator:'Personal Data Protection Authority (PDPA)', instrument:'Bahrain PDPL, Law No. 30 of 2018 (in force 1 Aug 2019)', binding:BINDING.STATUTE, trigger:'processes_bahrain_resident_data', evidence:['public-facing privacy notice (purposes, lawful basis, data-subject rights)'], detect:'Bahrain nexus AND privacy-notice present/absent', enforcement:'PDPA administrative penalties; criminal liability for serious breaches.', jurisdiction:'BH', updated:'2019-08-01' },
  OMAN_PDPL: { regulator:'Ministry of Transport, Communications & IT (MTCIT)', instrument:'Oman PDPL, Royal Decree 6/2022 (fully enforceable 5 Feb 2026)', binding:BINDING.STATUTE, trigger:'processes_oman_resident_data', evidence:['public-facing privacy notice'], detect:'Oman nexus AND privacy-notice present/absent', enforcement:'MTCIT penalties; fines up to OMR 500,000.', jurisdiction:'OM', updated:'2026-02-05' },
  EGYPT_PDPL: { regulator:'Personal Data Protection Centre (PDPC)', instrument:'Egypt PDPL, Law No. 151 of 2020 (Exec Regs Decree 816/2025)', binding:BINDING.STATUTE, trigger:'processes_egypt_resident_data', evidence:['public-facing privacy notice'], detect:'Egypt nexus AND privacy-notice present/absent', enforcement:'PDPC fines and criminal penalties.', jurisdiction:'EG', updated:'2020-10-15' },
  JORDAN_PDPL: { regulator:'Data Protection Council (MoDEE)', instrument:'Jordan PDPL, Law No. 24 of 2023 (in force 17 Mar 2024)', binding:BINDING.STATUTE, trigger:'processes_jordan_resident_data', evidence:['public-facing privacy notice'], detect:'Jordan nexus AND privacy-notice present/absent', enforcement:'Data Protection Council fines.', jurisdiction:'JO', updated:'2024-03-17' },
  ISRAEL_PPL: { regulator:'Privacy Protection Authority (PPA)', instrument:'Israel Protection of Privacy Law 5741-1981, Amendment 13 (effective 14 Aug 2025)', binding:BINDING.STATUTE, trigger:'processes_israel_resident_data', evidence:['public-facing privacy notice'], detect:'Israel nexus AND privacy-notice present/absent', enforcement:'PPA administrative fines (substantially increased by Amendment 13).', jurisdiction:'IL', updated:'2025-08-14' }
};

function frameworkIntel(code){ return INTEL[code] || null; }
function bindingStatus(code){ const r = INTEL[code]; return r ? r.binding : null; }
function isVoluntary(code){ return bindingStatus(code) === BINDING.VOLUNTARY; }
const ALL_INTEL_CODES = Object.keys(INTEL);

module.exports = { INTEL, BINDING, frameworkIntel, bindingStatus, isVoluntary, ALL_INTEL_CODES };
