#!/usr/bin/env node
// Tamazia nightly metrics rollup (P3-5) · aggregates deliverability + cost per SOURCE and per PIPELINE
// (= sector) from sends / bounce_events / inbound_emails / lead_sources / leads, and writes one snapshot
// row per (metric_date, source, pipeline) into the `metrics` table. This feeds Metabase + the tamazia-ops MCP.
//
// IDEMPOTENT per metric_date: a UNIQUE (metric_date, source, pipeline) key + ON CONFLICT DO UPDATE means
// re-running the same day overwrites that day's rows (never duplicates). Default metric_date = today (UTC).
//
// Three row families are written each run:
//   - one OVERALL row:           source='all',     pipeline='all'        (totals across every send)
//   - one row PER SOURCE:        source=<src>,     pipeline='all'        (deliverability + cost-per-lead by source)
//   - one row PER PIPELINE:      source='all',     pipeline=<sector>     (deliverability by sector campaign)
//
// REALITY (verified live, see ops/PRECHECK-obs.md / observability/dashboards.md): sends.lead_id is NULL on
// every row today and the recipient->lead-email fallback also matches ~nothing, so send attribution mostly
// lands in 'unknown'. The joins below try lead_id FIRST then the email fallback, so per-source/per-sector
// numbers tighten automatically once the engine stamps lead_id — no code change needed here. The overall row
// is always correct (it does not depend on attribution). cost_per_lead uses lead_sources.cost_per_month_gbp /
// leads-sourced-for-that-source (a monthly cost spread over lifetime leads); free sources => 0.00; a source
// with no lead_sources row => NULL (unknown, never guessed).
//
// Fail-open: no NEON_URL or any DB error -> log + exit 0. A reporting job must never block or fail the cycle.
//
// Usage:
//   node scripts/compute-metrics.js            # metric_date = today (UTC)
//   node scripts/compute-metrics.js 2026-06-14 # backfill a specific date (rows still reflect data as-of now)
//   node scripts/compute-metrics.js --dry-run  # print the rows it WOULD write, touch nothing

const path = require('path');
const fs = require('fs');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
// Load .env like the sibling scripts (heartbeat.js / check-stuck-jobs.js): file values do not clobber an
// already-exported env var, so a value injected by the workflow (which sources .env) still wins.
(() => {
  try {
    const t = fs.readFileSync(path.join(ROOT, '.env'), 'utf8');
    for (const l of t.split('\n')) { const m = l.match(/^\s*([A-Z0-9_]+)\s*=\s*(.+?)\s*$/); if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^['"]|['"]$/g, ''); }
  } catch (_e) {}
})();

const NEON = process.env.NEON_URL || process.env.NEON_CONNECTION_STRING;

const args = process.argv.slice(2);
const DRY = args.includes('--dry-run') || args.includes('-n');
const dateArg = args.find(a => /^\d{4}-\d{2}-\d{2}$/.test(a));
const METRIC_DATE = dateArg || new Date().toISOString().slice(0, 10); // UTC today

function pg(sql) {
  if (!NEON) return null;
  try { return execFileSync(path.join(ROOT, 'scripts', 'psql'), [NEON, '-tA', '-c', sql], { encoding: 'utf8' }).toString().trim(); }
  catch (e) { console.error('[compute-metrics] query failed (fail-open):', (e && e.message || '').split('\n')[0]); return null; }
}
function rows(sql) { const r = pg(sql); return r == null || r === '' ? [] : r.split('\n').map(l => l.split('\t')); }
const esc = v => v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;
const numOrNull = v => (v == null || v === '' || v === 'NULL') ? 'NULL' : (Number(v).toString());
const pct = (n, d) => d > 0 ? +(100 * n / d).toFixed(2) : null;

// Belt-and-braces: the table is in schema/canonical-schema.{json,sql} (ensure-schema provisions it), but a
// fresh DB or an out-of-band run should never error here. CREATE IF NOT EXISTS is a no-op when it already exists.
function ensure() {
  pg(`CREATE TABLE IF NOT EXISTS metrics (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        metric_date date DEFAULT CURRENT_DATE NOT NULL,
        source text DEFAULT 'all' NOT NULL,
        pipeline text DEFAULT 'all' NOT NULL,
        sent integer DEFAULT 0,
        bounced integer DEFAULT 0,
        replied integer DEFAULT 0,
        bounce_rate numeric(6,2),
        reply_rate numeric(6,2),
        cost_per_lead numeric(10,2),
        computed_at timestamptz DEFAULT now(),
        CONSTRAINT metrics_date_source_pipeline_key UNIQUE (metric_date, source, pipeline))`);
}

// ---- aggregation SQL (read-only; joins copied from the live-verified observability/dashboards.md) ----

// A send is "bounced" if it has a bounced_at, OR its delivery_status/status mentions a bounce, OR a
// bounce_events row points at it (send_id). Attribution: the send's lead via lead_id first, else recipient email.
const SQL_PER_SOURCE = `
WITH s AS (
  SELECT se.id,
         (se.bounced_at IS NOT NULL
            OR COALESCE(se.delivery_status,'') ILIKE '%bounce%'
            OR COALESCE(se.status,'')          ILIKE '%bounce%'
            OR EXISTS (SELECT 1 FROM bounce_events be WHERE be.send_id = se.id)) AS bounced,
         (se.replied_at IS NOT NULL) AS replied,
         COALESCE(l.source, l.acquisition_channel, '(unknown)') AS src
  FROM sends se
  LEFT JOIN leads l
    ON l.id = se.lead_id
    OR (se.lead_id IS NULL
        AND lower(COALESCE(NULLIF(se.recipient,''),'~none~')) = lower(COALESCE(l.email, l.contact_email, l.primary_email, '~no~')))
  WHERE se.sent_at IS NOT NULL
),
reps AS (
  SELECT COALESCE(l.source, l.acquisition_channel, '(unknown)') AS src, COUNT(*) AS replied
  FROM inbound_emails ie
  JOIN leads l ON l.id = ie.matched_lead_id
  WHERE ie.matched_lead_id IS NOT NULL
    AND COALESCE(ie.stop_keyword_detected,false) = false
    AND COALESCE(ie.bounce_detected,false)       = false
  GROUP BY 1
),
leadcost AS (
  SELECT COALESCE(NULLIF(l.source,''), l.acquisition_channel, '(unknown)') AS src,
         COUNT(*) AS leads, MAX(ls.cost_per_month_gbp) AS cost_gbp
  FROM leads l
  LEFT JOIN lead_sources ls ON ls.source = l.source
  GROUP BY 1
)
SELECT s.src,
       COUNT(*)                                  AS sent,
       COUNT(*) FILTER (WHERE s.bounced)         AS bounced,
       COALESCE(MAX(r.replied),0)                AS replied,
       lc.leads                                  AS leads,
       lc.cost_gbp                               AS cost_gbp
FROM s
LEFT JOIN reps r     ON r.src  = s.src
LEFT JOIN leadcost lc ON lc.src = s.src
GROUP BY s.src, lc.leads, lc.cost_gbp
ORDER BY sent DESC, s.src`;

// Per-pipeline = per-sector. Sector from the send's stamped sector, falling back to the matched lead's sector.
const SQL_PER_PIPELINE = `
WITH s AS (
  SELECT se.id,
         COALESCE(NULLIF(se.sector,''), l.sector, '(unknown)') AS pipeline,
         (se.bounced_at IS NOT NULL
            OR COALESCE(se.delivery_status,'') ILIKE '%bounce%'
            OR COALESCE(se.status,'')          ILIKE '%bounce%'
            OR EXISTS (SELECT 1 FROM bounce_events be WHERE be.send_id = se.id)) AS bounced,
         (se.replied_at IS NOT NULL) AS replied
  FROM sends se
  LEFT JOIN leads l
    ON l.id = se.lead_id
    OR (se.lead_id IS NULL
        AND lower(COALESCE(NULLIF(se.recipient,''),'~none~')) = lower(COALESCE(l.email, l.contact_email, l.primary_email, '~no~')))
  WHERE se.sent_at IS NOT NULL
)
SELECT pipeline,
       COUNT(*)                          AS sent,
       COUNT(*) FILTER (WHERE bounced)   AS bounced,
       COUNT(*) FILTER (WHERE replied)   AS replied
FROM s
GROUP BY pipeline
ORDER BY sent DESC, pipeline`;

// Overall = every send, no attribution needed (always correct even while lead_id is NULL).
const SQL_OVERALL = `
SELECT COUNT(*) AS sent,
       COUNT(*) FILTER (WHERE se.bounced_at IS NOT NULL
            OR COALESCE(se.delivery_status,'') ILIKE '%bounce%'
            OR COALESCE(se.status,'')          ILIKE '%bounce%'
            OR EXISTS (SELECT 1 FROM bounce_events be WHERE be.send_id = se.id)) AS bounced,
       (SELECT COUNT(*) FROM inbound_emails ie
          WHERE ie.matched_lead_id IS NOT NULL
            AND COALESCE(ie.stop_keyword_detected,false)=false
            AND COALESCE(ie.bounce_detected,false)=false) AS replied
FROM sends se
WHERE se.sent_at IS NOT NULL`;

function buildRows() {
  const out = [];

  // Overall
  const ov = rows(SQL_OVERALL)[0] || ['0', '0', '0'];
  const oSent = Number(ov[0]) || 0, oBounced = Number(ov[1]) || 0, oReplied = Number(ov[2]) || 0;
  out.push({ source: 'all', pipeline: 'all', sent: oSent, bounced: oBounced, replied: oReplied,
             bounce_rate: pct(oBounced, oSent), reply_rate: pct(oReplied, oSent), cost_per_lead: null });

  // Per source
  for (const r of rows(SQL_PER_SOURCE)) {
    const [src, sent, bounced, replied, leads, costGbp] = r;
    const sN = Number(sent) || 0, bN = Number(bounced) || 0, rN = Number(replied) || 0;
    const leadsN = Number(leads) || 0;
    const cost = (costGbp == null || costGbp === '' || costGbp === 'NULL') ? null : Number(costGbp);
    const cpl = (cost == null) ? null : (leadsN > 0 ? +(cost / leadsN).toFixed(2) : null);
    out.push({ source: src || '(unknown)', pipeline: 'all', sent: sN, bounced: bN, replied: rN,
               bounce_rate: pct(bN, sN), reply_rate: pct(rN, sN), cost_per_lead: cpl });
  }

  // Per pipeline (sector)
  for (const r of rows(SQL_PER_PIPELINE)) {
    const [pipeline, sent, bounced, replied] = r;
    const sN = Number(sent) || 0, bN = Number(bounced) || 0, rN = Number(replied) || 0;
    out.push({ source: 'all', pipeline: pipeline || '(unknown)', sent: sN, bounced: bN, replied: rN,
               bounce_rate: pct(bN, sN), reply_rate: pct(rN, sN), cost_per_lead: null });
  }
  return out;
}

function upsert(r) {
  pg(`INSERT INTO metrics (metric_date, source, pipeline, sent, bounced, replied, bounce_rate, reply_rate, cost_per_lead, computed_at)
      VALUES (${esc(METRIC_DATE)}, ${esc(r.source)}, ${esc(r.pipeline)}, ${r.sent | 0}, ${r.bounced | 0}, ${r.replied | 0},
              ${numOrNull(r.bounce_rate)}, ${numOrNull(r.reply_rate)}, ${numOrNull(r.cost_per_lead)}, now())
      ON CONFLICT (metric_date, source, pipeline) DO UPDATE SET
        sent=EXCLUDED.sent, bounced=EXCLUDED.bounced, replied=EXCLUDED.replied,
        bounce_rate=EXCLUDED.bounce_rate, reply_rate=EXCLUDED.reply_rate,
        cost_per_lead=EXCLUDED.cost_per_lead, computed_at=now()`);
}

function main() {
  if (!NEON) { console.log('[compute-metrics] no NEON_URL — skipping (fail-open)'); return; }
  ensure();
  const all = buildRows();
  if (DRY) {
    console.log(`[compute-metrics] DRY RUN for metric_date=${METRIC_DATE} — ${all.length} rows (nothing written):`);
    for (const r of all) console.log('  ' + JSON.stringify(r));
    return;
  }
  let n = 0;
  for (const r of all) { upsert(r); n++; }
  const overall = all[0];
  console.log(`[compute-metrics] metric_date=${METRIC_DATE}: wrote ${n} rows ` +
    `(overall: ${overall.sent} sent / ${overall.bounced} bounced / ${overall.replied} replied; ` +
    `${all.filter(x => x.pipeline === 'all' && x.source !== 'all').length} sources, ` +
    `${all.filter(x => x.source === 'all' && x.pipeline !== 'all').length} pipelines).`);
}

try { main(); } catch (e) { console.error('[compute-metrics] fatal (fail-open):', e && e.message); }
process.exit(0);
