#!/usr/bin/env node
// Tamazia engine heartbeat · one row per JOB run in engine_runs (start + finish), so engine_health,
// the tamazia-ops MCP, and the stuck-job detector can see which engines ran, when, and how they ended.
// Fail-open: any DB error is swallowed and never blocks the job. Reuses scripts/psql + NEON_URL,
// exactly like health-check.js / intel-pulse.js.
//
//   node scripts/heartbeat.js start <job> [host]                         -> prints the new run id (stdout)
//   node scripts/heartbeat.js finish <id> [status] [processed] [errors] [last_error...]
//   node scripts/heartbeat.js wrap <job> -- <command...>                 -> start, run, finish (status from exit code)
//
// engine_runs is also in schema/canonical-schema.json, so ensure-schema.js provisions it; the CREATE
// here is a fail-open belt-and-braces so a heartbeat never errors on a fresh DB.

const path = require('path');
const fs = require('fs');
const os = require('os');
const { execFileSync, spawnSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const ENV = {};
try { for (const l of fs.readFileSync(path.join(ROOT, '.env'), 'utf8').split('\n')) { const m = l.match(/^\s*([A-Z0-9_]+)\s*=\s*(.+?)\s*$/); if (m) ENV[m[1]] = m[2].replace(/^['"]|['"]$/g, ''); } } catch (_e) {}
const NEON = ENV.NEON_URL || process.env.NEON_URL;
const HOST = (process.env.GITHUB_WORKFLOW ? 'gh-actions' : (process.env.HOSTNAME || os.hostname() || 'vm'));

function pg(sql) { if (!NEON) return null; try { return execFileSync(path.join(ROOT, 'scripts', 'psql'), [NEON, '-tA', '-c', sql], { encoding: 'utf8' }).toString().trim(); } catch (_e) { return null; } }
const esc = v => v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;

function ensure() {
  pg(`CREATE TABLE IF NOT EXISTS engine_runs (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job text NOT NULL, host text, started_at timestamptz DEFAULT now() NOT NULL, finished_at timestamptz, status text DEFAULT 'running', processed integer DEFAULT 0, errors integer DEFAULT 0, last_error text, meta jsonb)`);
}

function start(job, host) {
  if (!job) { console.error('heartbeat start: job required'); return ''; }
  ensure();
  const r = pg(`INSERT INTO engine_runs (job,host,status) VALUES (${esc(job)},${esc(host || HOST)},'running') RETURNING id`);
  return r ? (r.split('\n')[0] || '').trim() : '';
}

function finish(id, status, processed, errors, lastError) {
  if (!id) return;
  const sets = ['finished_at=now()', `status=${esc(status || 'ok')}`];
  if (processed != null && processed !== '') sets.push(`processed=${Number(processed) || 0}`);
  if (errors != null && errors !== '') sets.push(`errors=${Number(errors) || 0}`);
  if (lastError) sets.push(`last_error=${esc(String(lastError).slice(0, 2000))}`);
  pg(`UPDATE engine_runs SET ${sets.join(',')} WHERE id=${Number(id) || 0}`);
}

function main() {
  const a = process.argv.slice(2);
  const mode = a[0];
  if (mode === 'start') { process.stdout.write(start(a[1], a[2])); return; }
  if (mode === 'finish') { finish(a[1], a[2], a[3], a[4], a.slice(5).join(' ')); return; }
  if (mode === 'wrap') {
    const sep = a.indexOf('--');
    const job = a[1];
    const cmd = sep >= 0 ? a.slice(sep + 1) : a.slice(2);
    if (!job || !cmd.length) { console.error('usage: heartbeat.js wrap <job> -- <command...>'); process.exit(2); }
    const id = start(job);
    // maxBuffer: `wrap` pipes the child's stdout+stderr so it can tail the last lines into engine_runs.last_error.
    // Wrapped jobs (scrapers, backlog-burst, intel-pulse, eval-audit, nightly-workers) emit verbose per-lead logs
    // that blow Node's 1MB default -> spawnSync sets status=null (ENOBUFS) + kills the child, so a SUCCESSFUL job
    // gets recorded as 'error', exits non-zero, and fires the failure-alert. 256MB makes the wrap output-safe.
    const r = spawnSync(cmd[0], cmd.slice(1), { stdio: ['inherit', 'pipe', 'pipe'], encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 });
    if (r.stdout) process.stdout.write(r.stdout);
    if (r.stderr) process.stderr.write(r.stderr);
    const ok = r.status === 0;
    const tail = ok ? null : (((r.stdout || '') + (r.stderr || '')).split('\n').filter(Boolean).slice(-3).join(' | ') || ('exit ' + r.status));
    finish(id, ok ? 'ok' : 'error', null, ok ? 0 : 1, tail);
    process.exit(r.status == null ? 1 : r.status);
  }
  console.error('usage: heartbeat.js start|finish|wrap');
  process.exit(2);
}

main();
