#!/usr/bin/env node
// Tamazia engine heartbeat · one row per JOB run in engine_runs (start + finish), so engine_health,
// the tamazia-ops MCP, and the stuck-job detector can see which engines ran, when, and how they ended.
// Fail-open: any DB error is swallowed and never blocks the job. Reuses scripts/psql + NEON_URL,
// exactly like health-check.js / intel-pulse.js.
//
//   node scripts/heartbeat.js start <job> [host]                         -> prints the new run id (stdout)
//   node scripts/heartbeat.js finish <id> [status] [processed] [errors] [last_error...]
//   node scripts/heartbeat.js wrap <job> -- <command...>                 -> start, run, finish (status from exit code)
//   node scripts/heartbeat.js active-writer                              -> prints a live heavy-writer job name, or '' (engine-cycle race guard)
//
// engine_runs is also in schema/canonical-schema.json, so ensure-schema.js provisions it; the CREATE
// here is a fail-open belt-and-braces so a heartbeat never errors on a fresh DB.

const path = require('path');
const fs = require('fs');
const os = require('os');
const { execFileSync, spawnSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const ENV = {};
try { for (const l of fs.readFileSync(path.join(ROOT, '.env'), 'utf8').split('\n')) { const m = l.match(/^\s*([A-Z0-9_]+)\s*=\s*(.+?)\s*$/); if (m) ENV[m[1]] = m[2].replace(/^['"]|['"]$/g, ''); } } catch (_e) {}
const NEON = ENV.NEON_URL || process.env.NEON_URL;
const HOST = (process.env.GITHUB_WORKFLOW ? 'gh-actions' : (process.env.HOSTNAME || os.hostname() || 'vm'));

function pg(sql) { if (!NEON) return null; try { return execFileSync(path.join(ROOT, 'scripts', 'psql'), [NEON, '-tA', '-c', sql], { encoding: 'utf8' }).toString().trim(); } catch (_e) { return null; } }
const esc = v => v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;

function ensure() {
  pg(`CREATE TABLE IF NOT EXISTS engine_runs (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job text NOT NULL, host text, started_at timestamptz DEFAULT now() NOT NULL, finished_at timestamptz, status text DEFAULT 'running', processed integer DEFAULT 0, errors integer DEFAULT 0, last_error text, meta jsonb)`);
}

// Reaper: a run killed before finish() (GitHub SIGKILL at the job timeout, an OOM, a hung step) leaves its
// engine_runs row stuck 'running' forever. Nothing else closes them, and check-stuck-jobs uses
// MAX(COALESCE(finished_at,started_at)), so a fresh zombie's started_at actually MASKS the stall and the job
// never alarms. We self-heal on the next start of the SAME job: any 'running' row for this job older than
// REAP_AFTER_MIN (default 90m, well past every workflow's job timeout: engine-cycle 25, backlog/v3 120 don't
// share this job name) is force-closed as 'killed'. Bounded to one job, time-gated, idempotent, fail-open.
const REAP_AFTER_MIN = Number(process.env.HEARTBEAT_REAP_AFTER_MIN || 90);
function reap(job) {
  pg(`UPDATE engine_runs SET status='killed', finished_at=now(),
        last_error=COALESCE(last_error,'reaped: no finish() before next start (killed/timeout)')
      WHERE job=${esc(job)} AND status='running' AND started_at < now() - interval '${REAP_AFTER_MIN} minutes'`);
}

function start(job, host) {
  if (!job) { console.error('heartbeat start: job required'); return ''; }
  ensure();
  reap(job);
  const r = pg(`INSERT INTO engine_runs (job,host,status) VALUES (${esc(job)},${esc(host || HOST)},'running') RETURNING id`);
  return r ? (r.split('\n')[0] || '').trim() : '';
}

function finish(id, status, processed, errors, lastError) {
  if (!id) return;
  const sets = ['finished_at=now()', `status=${esc(status || 'ok')}`];
  if (processed != null && processed !== '') sets.push(`processed=${Number(processed) || 0}`);
  if (errors != null && errors !== '') sets.push(`errors=${Number(errors) || 0}`);
  if (lastError) sets.push(`last_error=${esc(String(lastError).slice(0, 2000))}`);
  pg(`UPDATE engine_runs SET ${sets.join(',')} WHERE id=${Number(id) || 0}`);
}

// Race guard for the engine cycle. The heavy re-tier writers (v3-rerun / v3-validate / backlog-burst /
// nightly-workers) rewrite icp_tier / quality_fit / lifecycle_stage / sector_code on
// the SAME rows the cycle's qualify->enqueue->mint->render seam reads+writes. They used to share the
// `engine-db-work` concurrency group with engine-cycle so the two never overlapped — but that group queued the
// every-30-min cycle behind ~5h v3-runs, and GitHub then CANCELLED the superseded pending cycles (founder-alarming
// "cancelled" runs). engine-cycle now has its OWN group (so it never self-cancels) and protects the race at the
// DATA layer instead: this prints the job name of an actively-running heavy writer (status='running' within a TTL),
// or '' if none. The cycle SKIPS just its race-sensitive steps when a writer is live, and runs everything else.
// TTL (default 360m) covers v3-rerun's 330m cap; the reaper independently force-closes truly-dead 'running' rows
// after 90m of the same job, so a crashed writer can never wedge the guard permanently. Fail-open: any DB error
// returns '' (cycle proceeds) — never block the cycle on the guard itself.
const WRITER_JOBS = ['v3-rerun', 'v3-validate', 'backlog-burst', 'nightly-workers'];
const WRITER_TTL_MIN = Number(process.env.ENGINE_WRITER_TTL_MIN || 360);
function activeWriter() {
  const list = WRITER_JOBS.map(esc).join(',');
  const r = pg(`SELECT job FROM engine_runs
      WHERE job IN (${list}) AND status='running' AND started_at > now() - interval '${WRITER_TTL_MIN} minutes'
      ORDER BY started_at DESC LIMIT 1`);
  return r ? (r.split('\n')[0] || '').trim() : '';
}

function main() {
  const a = process.argv.slice(2);
  const mode = a[0];
  if (mode === 'start') { process.stdout.write(start(a[1], a[2])); return; }
  if (mode === 'finish') { finish(a[1], a[2], a[3], a[4], a.slice(5).join(' ')); return; }
  if (mode === 'active-writer') { process.stdout.write(activeWriter()); return; }   // race guard for the engine cycle (see activeWriter())
  if (mode === 'wrap') {
    const sep = a.indexOf('--');
    const job = a[1];
    const cmd = sep >= 0 ? a.slice(sep + 1) : a.slice(2);
    if (!job || !cmd.length) { console.error('usage: heartbeat.js wrap <job> -- <command...>'); process.exit(2); }
    const id = start(job);
    // maxBuffer: `wrap` pipes the child's stdout+stderr so it can tail the last lines into engine_runs.last_error.
    // Wrapped jobs (scrapers, backlog-burst, intel-pulse, eval-audit, nightly-workers) emit verbose per-lead logs
    // that blow Node's 1MB default -> spawnSync sets status=null (ENOBUFS) + kills the child, so a SUCCESSFUL job
    // gets recorded as 'error', exits non-zero, and fires the failure-alert. 256MB makes the wrap output-safe.
    // Hung-step guard: ALSO bound the wrapped command so a hung child (stuck network call, dead socket) can
    // never wedge the wrap past the workflow timeout — we close the heartbeat row as 'error' instead.
    // Default 20min (under the tightest wrapper workflow timeout); override with HEARTBEAT_WRAP_TIMEOUT_MS.
    const wrapTimeout = Math.max(0, Number(process.env.HEARTBEAT_WRAP_TIMEOUT_MS || 1200000)) || undefined;
    const r = spawnSync(cmd[0], cmd.slice(1), { stdio: ['inherit', 'pipe', 'pipe'], encoding: 'utf8', maxBuffer: 256 * 1024 * 1024, timeout: wrapTimeout, killSignal: 'SIGKILL' });
    if (r.stdout) process.stdout.write(r.stdout);
    if (r.stderr) process.stderr.write(r.stderr);
    const timedOut = r.error && (r.error.code === 'ETIMEDOUT' || r.signal === 'SIGKILL');
    const ok = r.status === 0 && !timedOut;
    const tail = ok ? null : (timedOut ? `timeout after ${wrapTimeout}ms` : (((r.stdout || '') + (r.stderr || '')).split('\n').filter(Boolean).slice(-3).join(' | ') || ('exit ' + r.status)));
    finish(id, ok ? 'ok' : 'error', null, ok ? 0 : 1, tail);
    process.exit(timedOut ? 124 : (r.status == null ? 1 : r.status));
  }
  console.error('usage: heartbeat.js start|finish|wrap|active-writer');
  process.exit(2);
}

main();
